<?php
$z[0]=Array("field","站长之家, 微商怎么做, 微",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近期和微商行业的朋友们交流的时候，大家都开始忧虑了，微商团队开始迷茫了，因为生意下滑得厉害，而且不是一般的不好，是非常差，差到不如之前的五分之一，想做微商的品牌",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","微商还有钱途 只是和你没关系",363,441);
$z[2][4]['name']="title";
$z[3]=Array("field","",443,482);
$z[3][4]['name']="writer";
$z[4]=Array("field","",484,523);
$z[4][4]['name']="source";
$z[5]=Array("field","",525,565);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",567,604);
$z[6][4]['name']="body";
$z[7]=Array("field","",606,645);
$z[7][4]['name']="litpic";

?>