{dede:field name='keywords'}站长之家, 二级域名, mal{/dede:field}
{dede:field name='description'}此前4月份，有消息称百度将在6月启用二级域名mall.baidu.com上线新的O2O电商平台“百度Mall”，当时域名尚不能访问。不过今日小编发现，该二级域名已经建站了。{/dede:field}
{dede:field name='title'}电商上不死心的百度启用二级域名建站了！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AY340-41023.png{/dede:field}
