<?php
$z[0]=Array("field","站长之家, 二级域名, mal",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","此前4月份，有消息称百度将在6月启用二级域名mall.baidu.com上线新的O2O电商平台“百度Mall”，当时域名尚不能访问。不过今日小编发现，该二级域名已经建站了。",74,330);
$z[1][4]['name']="description";
$z[2]=Array("field","电商上不死心的百度启用二级域名建站了！",332,427);
$z[2][4]['name']="title";
$z[3]=Array("field","",429,468);
$z[3][4]['name']="writer";
$z[4]=Array("field","",470,509);
$z[4][4]['name']="source";
$z[5]=Array("field","",511,551);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",553,590);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AY340-41023.png",592,676);
$z[7][4]['name']="litpic";

?>