<?php
$z[0]=Array("field","站长之家, 携程网瘫痪, 携",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","点击进入携程网，页面显示404报错，虽然点击“返回首页”后依然可以进入携程网，但其功能和其它链接均无法使用。",77,277);
$z[1][4]['name']="description";
$z[2]=Array("field","非服务器攻击 传携程全线瘫痪因代码被恶意删除",279,381);
$z[2][4]['name']="title";
$z[3]=Array("field","",383,422);
$z[3][4]['name']="writer";
$z[4]=Array("field","",424,463);
$z[4][4]['name']="source";
$z[5]=Array("field","",465,505);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",507,544);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C63350-43625.jpg",546,631);
$z[7][4]['name']="litpic";

?>