{dede:field name='keywords'}站长之家, 周鸿祎, qiku.c{/dede:field}
{dede:field name='description'}月初，360周鸿祎召开了一场“没有手机的手机发布会”，确定手机品牌“奇酷”，在向苹果致敬的同时还不忘吐糟小米等同行。他还说被启用建站的域名qiku.com早在10年前就在他{/dede:field}
{dede:field name='title'}周鸿祎谈域名：qiku.com 10年前就在我手中了？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425A61440-11439.png{/dede:field}
