<?php
$z[0]=Array("field","站长之家, 周鸿祎, qiku.c",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","月初，360周鸿祎召开了一场“没有手机的手机发布会”，确定手机品牌“奇酷”，在向苹果致敬的同时还不忘吐糟小米等同行。他还说被启用建站的域名qiku.com早在10年前就在他",74,350);
$z[1][4]['name']="description";
$z[2]=Array("field","周鸿祎谈域名：qiku.com 10年前就在我手中了？",352,449);
$z[2][4]['name']="title";
$z[3]=Array("field","",451,490);
$z[3][4]['name']="writer";
$z[4]=Array("field","",492,531);
$z[4][4]['name']="source";
$z[5]=Array("field","",533,573);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",575,612);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425A61440-11439.png",614,699);
$z[7][4]['name']="litpic";

?>