<?php
$z[0]=Array("field","站长之家, 微商怎么做, 微",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","思埠首创，传统企业韩束跟进的微商模式，目前80%微商都采取的微商模式，特点是3层或多层级分销，以找代理为主、卖货为辅的微商模式。不能定义为传销，，不是传销，但采用了",77,359);
$z[1][4]['name']="description";
$z[2]=Array("field","截止2015年6月20种微商细分模式总结",361,445);
$z[2][4]['name']="title";
$z[3]=Array("field","",447,486);
$z[3][4]['name']="writer";
$z[4]=Array("field","",488,527);
$z[4][4]['name']="source";
$z[5]=Array("field","",529,569);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",571,608);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BP3Z-14148.jpg",610,693);
$z[7][4]['name']="litpic";

?>