<?php
$z[0]=Array("field","站长之家, 只是, 钱途",0,69);
$z[0][4]['name']="keywords";
$z[1]=Array("field","微商这几个月业绩急转直下的过程其实是微商行业成熟的过程。",71,199);
$z[1][4]['name']="description";
$z[2]=Array("field","微商还有钱途，只是和你没关系",201,281);
$z[2][4]['name']="title";
$z[3]=Array("field","",283,322);
$z[3][4]['name']="writer";
$z[4]=Array("field","",324,363);
$z[4][4]['name']="source";
$z[5]=Array("field","",365,405);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",407,444);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BX060-14595.jpg",446,530);
$z[7][4]['name']="litpic";

?>