{dede:field name='keywords'}站长之家, 百度推荐, 网站{/dede:field}
{dede:field name='description'}前几天笔者还在纠结网站要不要使用百度推荐?毕竟这是在页面调用js代码，对搜索引擎用处不大。考虑到用户体验，能够给用户展示更多的文章，提升网站浏览量，最后决定使用。{/dede:field}
{dede:field name='title'}亲身经历：使用百度推荐的一些体会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425CL910-125N.jpg{/dede:field}
