<?php
$z[0]=Array("field","站长之家, 百度推荐, 网站",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","前几天笔者还在纠结网站要不要使用百度推荐?毕竟这是在页面调用js代码，对搜索引擎用处不大。考虑到用户体验，能够给用户展示更多的文章，提升网站浏览量，最后决定使用。",77,358);
$z[1][4]['name']="description";
$z[2]=Array("field","亲身经历：使用百度推荐的一些体会",360,446);
$z[2][4]['name']="title";
$z[3]=Array("field","",448,487);
$z[3][4]['name']="writer";
$z[4]=Array("field","",489,528);
$z[4][4]['name']="source";
$z[5]=Array("field","",530,570);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",572,609);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425CL910-125N.jpg",611,694);
$z[7][4]['name']="litpic";

?>