<?php
$z[0]=Array("field","站长之家, 域名交易, 域名",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","昨日，奇酷科技完成了对大神手机的收购，至此原为酷派旗下的大神手机正式并入了奇酷科技，360周鸿祎将直接操刀这两个手机品牌。奇酷域名qiku.com目前正在为奇酷手机的基础",77,354);
$z[1][4]['name']="description";
$z[2]=Array("field","奇酷收购大神手机 域名qiku.com建众筹计划",356,448);
$z[2][4]['name']="title";
$z[3]=Array("field","",450,489);
$z[3][4]['name']="writer";
$z[4]=Array("field","",491,530);
$z[4][4]['name']="source";
$z[5]=Array("field","",532,572);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",574,611);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BJc0-41415.png",613,696);
$z[7][4]['name']="litpic";

?>