{dede:field name='keywords'}站长之家, 域名交易, 域名{/dede:field}
{dede:field name='description'}昨日，奇酷科技完成了对大神手机的收购，至此原为酷派旗下的大神手机正式并入了奇酷科技，360周鸿祎将直接操刀这两个手机品牌。奇酷域名qiku.com目前正在为奇酷手机的基础{/dede:field}
{dede:field name='title'}奇酷收购大神手机 域名qiku.com建众筹计划{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425BJc0-41415.png{/dede:field}
