{dede:field name='keywords'}站长之家, 人人退市, 人人{/dede:field}
{dede:field name='description'}不管退市是不是为了回内地上市，人人网都已经不再是当年上市之时那个所谓中国的 Facebook 了。{/dede:field}
{dede:field name='title'}人人要退市，你知道过去 4 年它做了几十个新产品么？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C243P-522M.jpg{/dede:field}
