<?php
$z[0]=Array("field","站长之家, 人人退市, 人人",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","不管退市是不是为了回内地上市，人人网都已经不再是当年上市之时那个所谓中国的 Facebook 了。",77,248);
$z[1][4]['name']="description";
$z[2]=Array("field","人人要退市，你知道过去 4 年它做了几十个新产品么？",250,360);
$z[2][4]['name']="title";
$z[3]=Array("field","",362,401);
$z[3][4]['name']="writer";
$z[4]=Array("field","",403,442);
$z[4][4]['name']="source";
$z[5]=Array("field","",444,484);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",486,523);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C243P-522M.jpg",525,608);
$z[7][4]['name']="litpic";

?>