<?php
$z[0]=Array("field","站长之家, 创业经验分享",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","这是一个最好的时代。移动互联网、大数据、云计算等技术让“弯道超车”的创业商机俯拾即是。在政策的扶持下，全球各地的孵化器、创业园如雨后春笋般涌现。资本市场上，集万",75,359);
$z[1][4]['name']="description";
$z[2]=Array("field","警惕！全民创业热潮背后暗藏着三大危险",361,453);
$z[2][4]['name']="title";
$z[3]=Array("field","",455,494);
$z[3][4]['name']="writer";
$z[4]=Array("field","",496,535);
$z[4][4]['name']="source";
$z[5]=Array("field","",537,577);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",579,616);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C40G0-4H05.jpg",618,701);
$z[7][4]['name']="litpic";

?>