{dede:field name='keywords'}站长之家, craig, 雅虎, 谷歌{/dede:field}
{dede:field name='description'}一位创业者 Craig Walker 的故事吸引了我，他先后创立了两家公司，分别被雅虎和 Google 收购，但这两次公司被收购后的经历却完全不一同。{/dede:field}
{dede:field name='title'}他创立了两家公司，分别卖给了雅虎和 Google{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C3N0-1LH.png{/dede:field}
