<?php
$z[0]=Array("field","站长之家, craig, 雅虎, 谷歌",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","一位创业者 Craig Walker 的故事吸引了我，他先后创立了两家公司，分别被雅虎和 Google 收购，但这两次公司被收购后的经历却完全不一同。",78,303);
$z[1][4]['name']="description";
$z[2]=Array("field","他创立了两家公司，分别卖给了雅虎和 Google",305,401);
$z[2][4]['name']="title";
$z[3]=Array("field","",403,442);
$z[3][4]['name']="writer";
$z[4]=Array("field","",444,483);
$z[4][4]['name']="source";
$z[5]=Array("field","",485,525);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",527,564);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C3N0-1LH.png",566,647);
$z[7][4]['name']="litpic";

?>