<?php
$z[0]=Array("field","站长之家, 阿里巴巴, 阿里",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","如果现在给运营狗们抛出一个问题：运营、营销、策划有什么区别？相信90%的人一口答不上来，脑子飞速的转个几分钟后，才能说几句营销偏资源啦，运营偏内容啦，策划偏创意啦",77,358);
$z[1][4]['name']="description";
$z[2]=Array("field","10W+阅读的好文 我在阿里做运营（一）",360,448);
$z[2][4]['name']="title";
$z[3]=Array("field","",450,489);
$z[3][4]['name']="writer";
$z[4]=Array("field","",491,530);
$z[4][4]['name']="source";
$z[5]=Array("field","",532,572);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",574,611);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BcC0-54406.jpg",613,696);
$z[7][4]['name']="litpic";

?>