{dede:field name='keywords'}站长之家, 阿里巴巴, 阿里{/dede:field}
{dede:field name='description'}如果现在给运营狗们抛出一个问题：运营、营销、策划有什么区别？相信90%的人一口答不上来，脑子飞速的转个几分钟后，才能说几句营销偏资源啦，运营偏内容啦，策划偏创意啦{/dede:field}
{dede:field name='title'}10W+阅读的好文 我在阿里做运营（一）{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425BcC0-54406.jpg{/dede:field}
