<?php
$z[0]=Array("field","站长之家, 推拿O2O, 上门推",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","九阿哥是一家专注办公室头颈肩的上门推拿O2O公司，成立于2014年11月，产品上线于2015年3月，创始人是臧洋洲，隶属于深圳市知行互动科技有限公司，目前主要在深圳提供服务。",77,354);
$z[1][4]['name']="description";
$z[2]=Array("field","深圳上门推拿O2O九阿哥：打造中国的Office Massage",356,456);
$z[2][4]['name']="title";
$z[3]=Array("field","",458,497);
$z[3][4]['name']="writer";
$z[4]=Array("field","",499,538);
$z[4][4]['name']="source";
$z[5]=Array("field","",540,580);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",582,619);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C23360-4La.png",621,704);
$z[7][4]['name']="litpic";

?>