{dede:field name='keywords'}站长之家, 推拿O2O, 上门推{/dede:field}
{dede:field name='description'}九阿哥是一家专注办公室头颈肩的上门推拿O2O公司，成立于2014年11月，产品上线于2015年3月，创始人是臧洋洲，隶属于深圳市知行互动科技有限公司，目前主要在深圳提供服务。{/dede:field}
{dede:field name='title'}深圳上门推拿O2O九阿哥：打造中国的Office Massage{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C23360-4La.png{/dede:field}
