<?php
$z[0]=Array("field","站长之家, AR游戏, VR, 互联",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","做AR游戏还要建仓库？AR小熊应用引爆朋友圈，但为什么说AR的游戏内容还不足以支撑一个产业的发展？游戏陀螺采访到了资深AR从业者陈坚，他认为：国前的AR根本没有产业链，还",77,356);
$z[1][4]['name']="description";
$z[2]=Array("field","一个AR从业者的自白：根本没有产业链，还不如转做VR",358,466);
$z[2][4]['name']="title";
$z[3]=Array("field","",468,507);
$z[3][4]['name']="writer";
$z[4]=Array("field","",509,548);
$z[4][4]['name']="source";
$z[5]=Array("field","",550,590);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",592,629);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C391F-2G29.jpg",631,714);
$z[7][4]['name']="litpic";

?>