{dede:field name='keywords'}站长之家, AR游戏, VR, 互联{/dede:field}
{dede:field name='description'}做AR游戏还要建仓库？AR小熊应用引爆朋友圈，但为什么说AR的游戏内容还不足以支撑一个产业的发展？游戏陀螺采访到了资深AR从业者陈坚，他认为：国前的AR根本没有产业链，还{/dede:field}
{dede:field name='title'}一个AR从业者的自白：根本没有产业链，还不如转做VR{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C391F-2G29.jpg{/dede:field}
