<?php
$z[0]=Array("field","站长之家, 微信运营, 微信",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","每当你费尽心思写下一篇文章，并拟好一个自认为合适的标题时，首先自己要学会换位思考，站在粉丝的立场和角度，看看粉丝会不会对这个感兴趣，也可以问下朋友或者同事，从他",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","微信运营：十大绝招快速提高微信公众号消息阅读量",363,470);
$z[2][4]['name']="title";
$z[3]=Array("field","",472,511);
$z[3][4]['name']="writer";
$z[4]=Array("field","",513,552);
$z[4][4]['name']="source";
$z[5]=Array("field","",554,594);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",596,633);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B9E60-3cb.png",635,717);
$z[7][4]['name']="litpic";

?>