<?php
$z[0]=Array("field","站长之家, 微商怎么做, 微",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","过去2014年微商这个名词特别火，过去的一年微商就像一匹狼，驰骋在草原上（移动互联网的浪潮上）给游牧民（传统电商）给黄羊（传统自闭的企业）遭受沉重一击。",77,341);
$z[1][4]['name']="description";
$z[2]=Array("field","微商运营：2015年微商怎么做战略篇",343,427);
$z[2][4]['name']="title";
$z[3]=Array("field","",429,468);
$z[3][4]['name']="writer";
$z[4]=Array("field","",470,509);
$z[4][4]['name']="source";
$z[5]=Array("field","",511,551);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",553,590);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AJJ0-53234.jpg",592,675);
$z[7][4]['name']="litpic";

?>