<?php
$z[0]=Array("field","站长之家, 微商怎么做, 微",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","关于微商的文章之前发过很多，今天和大家分享一些关于微商团队的知识。很多人都想找一个牛逼的微商团队合作，或者自己能有一个牛逼的微商团队，那么牛逼的微商团队是怎样炼",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","纯干货：牛逼的微商团队是如何炼成的？",363,455);
$z[2][4]['name']="title";
$z[3]=Array("field","",457,496);
$z[3][4]['name']="writer";
$z[4]=Array("field","",498,537);
$z[4][4]['name']="source";
$z[5]=Array("field","",539,579);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",581,618);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BYa0-31G3.jpg",620,702);
$z[7][4]['name']="litpic";

?>