<?php
$z[0]=Array("field","站长之家, 姚劲波, 刘强东",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","后来，58同城账上真的一分钱都没有了。姚劲波卖了个域名，换了几十万出来给大家发工资。他们几个人就在旁边的咖啡厅见面，其他几个人都要走，姚劲波咣当就给搞哭了，说你们",77,360);
$z[1][4]['name']="description";
$z[2]=Array("field","58艰难期：姚劲波卖1个域名换几十万发工资",362,457);
$z[2][4]['name']="title";
$z[3]=Array("field","",459,498);
$z[3][4]['name']="writer";
$z[4]=Array("field","",500,539);
$z[4][4]['name']="source";
$z[5]=Array("field","",541,581);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",583,620);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B2U40-42441.png",622,706);
$z[7][4]['name']="litpic";

?>