{dede:field name='keywords'}站长之家, 姚劲波, 刘强东{/dede:field}
{dede:field name='description'}后来，58同城账上真的一分钱都没有了。姚劲波卖了个域名，换了几十万出来给大家发工资。他们几个人就在旁边的咖啡厅见面，其他几个人都要走，姚劲波咣当就给搞哭了，说你们{/dede:field}
{dede:field name='title'}58艰难期：姚劲波卖1个域名换几十万发工资{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B2U40-42441.png{/dede:field}
