{dede:field name='keywords'}站长之家, 创业者, 融资{/dede:field}
{dede:field name='description'}一堆VC出来说的话，你别太当真。尤其是很多投资经理、总监、副总、甚至合伙人级别的，扒开外衣其实还是打工的（此处必须吐槽一下VC的tittle问题）。{/dede:field}
{dede:field name='title'}创业者如何融资：相信自己，让竞争对手当垫背，营收是必杀{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C1SZ-59110.jpg{/dede:field}
