<?php
$z[0]=Array("field","站长之家, 创业者, 融资",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","一堆VC出来说的话，你别太当真。尤其是很多投资经理、总监、副总、甚至合伙人级别的，扒开外衣其实还是打工的（此处必须吐槽一下VC的tittle问题）。",74,320);
$z[1][4]['name']="description";
$z[2]=Array("field","创业者如何融资：相信自己，让竞争对手当垫背，营收是必杀",322,441);
$z[2][4]['name']="title";
$z[3]=Array("field","",443,482);
$z[3][4]['name']="writer";
$z[4]=Array("field","",484,523);
$z[4][4]['name']="source";
$z[5]=Array("field","",525,565);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",567,604);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C1SZ-59110.jpg",606,689);
$z[7][4]['name']="litpic";

?>