<?php
$z[0]=Array("field","站长之家, 新媒体运营, 创",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","四年大学，毕业从帝都回到县城，每个人都问我：为什么回来？两年后辞职回到帝都，更多人问：为什么又回去？",77,271);
$z[1][4]['name']="description";
$z[2]=Array("field","从公务员到新媒体运营，6倍薪水是怎样炼成的",273,372);
$z[2][4]['name']="title";
$z[3]=Array("field","",374,413);
$z[3][4]['name']="writer";
$z[4]=Array("field","",415,454);
$z[4][4]['name']="source";
$z[5]=Array("field","",456,496);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",498,535);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C2R60-262G.jpg",537,620);
$z[7][4]['name']="litpic";

?>