<?php
$z[0]=Array("field","站长之家, 无人机, 域名交",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","史诗级灾难大片《高考》在经过两天的全国公映后即将下档，而在这场一年一度的大片中，不仅有全国上百万的高三学子家长的倾情加盟，连高大上的无人机都亲自出马担任监考一职",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","高考无人机防作弊 域名wurenji.cn售5位数",363,452);
$z[2][4]['name']="title";
$z[3]=Array("field","",454,493);
$z[3][4]['name']="writer";
$z[4]=Array("field","",495,534);
$z[4][4]['name']="source";
$z[5]=Array("field","",536,576);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",578,615);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B5910-491G.jpg",617,700);
$z[7][4]['name']="litpic";

?>