<?php
$z[0]=Array("field","站长之家, Beijing.com, 域名",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","国内城市域名尤其是比较著名的城市，诸如首都北京、上海等此类一线城市域名更是借着其地区优越性而价格不菲。早在2001年，beijing和shanghai.com一起被香港某家公司拍",76,341);
$z[1][4]['name']="description";
$z[2]=Array("field","城市域名中的“高富帅”你造吗？",343,426);
$z[2][4]['name']="title";
$z[3]=Array("field","",428,467);
$z[3][4]['name']="writer";
$z[4]=Array("field","",469,508);
$z[4][4]['name']="source";
$z[5]=Array("field","",510,550);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",552,589);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AP2F-49632.png",591,674);
$z[7][4]['name']="litpic";

?>