{dede:field name='keywords'}站长之家, Beijing.com, 域名{/dede:field}
{dede:field name='description'}国内城市域名尤其是比较著名的城市，诸如首都北京、上海等此类一线城市域名更是借着其地区优越性而价格不菲。早在2001年，beijing和shanghai.com一起被香港某家公司拍{/dede:field}
{dede:field name='title'}城市域名中的“高富帅”你造吗？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AP2F-49632.png{/dede:field}
