{dede:field name='keywords'}站长之家, 域名投资, 域名{/dede:field}
{dede:field name='description'}近日，一条微博在圈内炸开了锅，引发了广大网友的关注和转发，同时也引发了我们对企业的域名使用及保护的进一步思考。{/dede:field}
{dede:field name='title'}从周鸿祎的怒骂看企业的域名使用及保护{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AFb0-25G8.jpg{/dede:field}
