<?php
$z[0]=Array("field","站长之家, 域名投资, 域名",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近日，一条微博在圈内炸开了锅，引发了广大网友的关注和转发，同时也引发了我们对企业的域名使用及保护的进一步思考。",77,286);
$z[1][4]['name']="description";
$z[2]=Array("field","从周鸿祎的怒骂看企业的域名使用及保护",288,380);
$z[2][4]['name']="title";
$z[3]=Array("field","",382,421);
$z[3][4]['name']="writer";
$z[4]=Array("field","",423,462);
$z[4][4]['name']="source";
$z[5]=Array("field","",464,504);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",506,543);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AFb0-25G8.jpg",545,627);
$z[7][4]['name']="litpic";

?>