<?php
$z[0]=Array("field","站长之家, 百度移动搜索",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","5月29日，百度站长平台在杭州举办了《移动搜索优化实用教程》专场培训，并以“解网站移动化之痛”为主题展开了讨论。会上，百度移动搜索技术总监王昊和百度移动搜索产品负",75,356);
$z[1][4]['name']="description";
$z[2]=Array("field","百度喜欢怎样的移动站？听移动搜索负责人怎么说",358,462);
$z[2][4]['name']="title";
$z[3]=Array("field","",464,503);
$z[3][4]['name']="writer";
$z[4]=Array("field","",505,544);
$z[4][4]['name']="source";
$z[5]=Array("field","",546,586);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",588,625);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425A96340-42019.png",627,712);
$z[7][4]['name']="litpic";

?>