{dede:field name='keywords'}2015百度联盟峰会{/dede:field}
{dede:field name='description'}李彦宏喜欢数理演算，也喜欢园艺，植树栽花。工程师、科学家的身份之外，李彦宏的另一个身份也是匠人、园丁。园艺培栽需要的是耐心与耐性，自然界的规律是春华秋实，急不来。{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
