<?php
$z[0]=Array("field","站长之家, 360.com, mi.com,",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","域名是一个网站的基石，其价值就等同于商标之于企业一般，地位置高不可言喻。所以，360才愿意用1700万美金买下360.com、苹果才会用600万美金为代价换取iCloud.com、小米才",73,342);
$z[1][4]['name']="description";
$z[2]=Array("field","全球最贵域名TOP 35：360.com第五 mi.com排27",344,434);
$z[2][4]['name']="title";
$z[3]=Array("field","",436,475);
$z[3][4]['name']="writer";
$z[4]=Array("field","",477,516);
$z[4][4]['name']="source";
$z[5]=Array("field","",518,558);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",560,597);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B93610-1UY.jpg",599,682);
$z[7][4]['name']="litpic";

?>