{dede:field name='keywords'}{##SiteKeyword##}{/dede:field}
{dede:field name='description'}{##SiteDescription##}{/dede:field}
{dede:field name='title'}紫御华府：采撷世界珍稀石材，书写豪宅新标准{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/14342460013P-23227.jpg{/dede:field}
