{dede:field name='keywords'}{##SiteKeyword##}{/dede:field}
{dede:field name='description'}{##SiteDescription##}{/dede:field}
{dede:field name='title'}石材的生命力 ——2015“文博会”广田分会场之环球石材研讨会{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143424600220-41032.jpg{/dede:field}
