<?php
$z[0]=Array("field","{##SiteKeyword##}",0,58);
$z[0][4]['name']="keywords";
$z[1]=Array("field","{##SiteDescription##}",60,125);
$z[1][4]['name']="description";
$z[2]=Array("field","石材的生命力 ——2015“文博会”广田分会场之环球石材研讨会",127,248);
$z[2][4]['name']="title";
$z[3]=Array("field","",250,289);
$z[3][4]['name']="writer";
$z[4]=Array("field","",291,330);
$z[4][4]['name']="source";
$z[5]=Array("field","",332,369);
$z[5][4]['name']="body";
$z[6]=Array("field","",371,411);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c150614/143424600220-41032.jpg",413,498);
$z[7][4]['name']="litpic";

?>