<?php
$z[0]=Array("field","站长之家, 暗网黑市, 暗网",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","这是一个真实的事件——暗网地下黑市中普通运营商之间的暗战。几周前，笔者曾发布了一篇关于新兴Tor地下黑市–TheRealDeal团队的分析报告，这是一个专营销售0day漏洞的团伙",77,352);
$z[1][4]['name']="description";
$z[2]=Array("field","揭秘：刀光剑影下的暗网黑市",354,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","",515,555);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",557,594);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BE3Z-39310.png",596,679);
$z[7][4]['name']="litpic";

?>