{dede:field name='keywords'}{##SiteKeyword##}{/dede:field}
{dede:field name='description'}{##SiteDescription##}{/dede:field}
{dede:field name='title'}成都通威国际中心{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/1434250491360-33252.jpg{/dede:field}
