{dede:field name='keywords'}站长之家, 支付宝, 携程网{/dede:field}
{dede:field name='description'}这两日最忙的两个终端，当属阿里和携程了。先是，支付宝出现故障，而后，携程则出现全线瘫痪。就连360好搜也在下午出现短暂瘫痪现象。网站瘫痪对用户和终端来说都是大忌，{/dede:field}
{dede:field name='title'}各家网站倒挂东南枝 光纤君：怪我咯！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425Cc060-13044.jpg{/dede:field}
