<?php
$z[0]=Array("field","站长之家, 支付宝, 携程网",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","这两日最忙的两个终端，当属阿里和携程了。先是，支付宝出现故障，而后，携程则出现全线瘫痪。就连360好搜也在下午出现短暂瘫痪现象。网站瘫痪对用户和终端来说都是大忌，",77,358);
$z[1][4]['name']="description";
$z[2]=Array("field","各家网站倒挂东南枝 光纤君：怪我咯！",360,450);
$z[2][4]['name']="title";
$z[3]=Array("field","",452,491);
$z[3][4]['name']="writer";
$z[4]=Array("field","",493,532);
$z[4][4]['name']="source";
$z[5]=Array("field","",534,574);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",576,613);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425Cc060-13044.jpg",615,699);
$z[7][4]['name']="litpic";

?>