<?php
$z[0]=Array("field","站长之家, 微店, 口袋购物",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","正处在风口中的微商再次迎来新一波的强劲增长，根据口袋购物旗下微店平台今天发布的一季度报告显示，2015年Q1季度微店新增用户超过900万。",77,310);
$z[1][4]['name']="description";
$z[2]=Array("field","谁在做微商？微店一季度统计数据告诉你",312,404);
$z[2][4]['name']="title";
$z[3]=Array("field","",406,445);
$z[3][4]['name']="writer";
$z[4]=Array("field","",447,486);
$z[4][4]['name']="source";
$z[5]=Array("field","",488,528);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",530,567);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425CGY0-42432.jpg",569,652);
$z[7][4]['name']="litpic";

?>