{dede:field name='keywords'}站长之家, 微店, 口袋购物{/dede:field}
{dede:field name='description'}正处在风口中的微商再次迎来新一波的强劲增长，根据口袋购物旗下微店平台今天发布的一季度报告显示，2015年Q1季度微店新增用户超过900万。{/dede:field}
{dede:field name='title'}谁在做微商？微店一季度统计数据告诉你{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425CGY0-42432.jpg{/dede:field}
