{dede:field name='keywords'}站长之家, 王思聪, bbbb.c{/dede:field}
{dede:field name='description'}上周，域名交易圈的头条绝对归国民老公王思聪所有，一个几十万的4叠字母bbbb.com就秒杀了所有的域名，完全将同样在近期交易，但交易价高达百万，甚至千万元的mj.com和mm.co{/dede:field}
{dede:field name='title'}被王思聪的bbbb.com抢了头条的千万2字母域名{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B34V0-2I36.jpg{/dede:field}
