<?php
$z[0]=Array("field","站长之家, 王思聪, bbbb.c",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","上周，域名交易圈的头条绝对归国民老公王思聪所有，一个几十万的4叠字母bbbb.com就秒杀了所有的域名，完全将同样在近期交易，但交易价高达百万，甚至千万元的mj.com和mm.co",74,348);
$z[1][4]['name']="description";
$z[2]=Array("field","被王思聪的bbbb.com抢了头条的千万2字母域名",350,445);
$z[2][4]['name']="title";
$z[3]=Array("field","",447,486);
$z[3][4]['name']="writer";
$z[4]=Array("field","",488,527);
$z[4][4]['name']="source";
$z[5]=Array("field","",529,569);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",571,608);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B34V0-2I36.jpg",610,693);
$z[7][4]['name']="litpic";

?>