<?php
$z[0]=Array("field","站长之家, 域名交易, 域名",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","年初时，4数字域名6262.com因一年价格翻涨了17万元，而受到不少米农的关注，当然类似的例子在域名交易市场上还有很多，那为什么他们的域名价格涨幅可以如此之大？谁又能来",77,354);
$z[1][4]['name']="description";
$z[2]=Array("field","饿死胆小的撑死胆大的！看别人如何投资域名赚钱",356,460);
$z[2][4]['name']="title";
$z[3]=Array("field","",462,501);
$z[3][4]['name']="writer";
$z[4]=Array("field","",503,542);
$z[4][4]['name']="source";
$z[5]=Array("field","",544,584);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",586,623);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C5N60-25130.jpg",625,709);
$z[7][4]['name']="litpic";

?>