<?php
$z[0]=Array("field","站长之家, yinyue.com, 音乐域",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","据whois资料显示，yinyue.com域名于昨日发生whois变更，目前所有人是4.CN ESCROW SERVICE，看来是由金名网中介的，据爆料，该域名为累主大神收购。",78,308);
$z[1][4]['name']="description";
$z[2]=Array("field","音乐域名yinyue.com易主 交易价达7位数",310,396);
$z[2][4]['name']="title";
$z[3]=Array("field","",398,437);
$z[3][4]['name']="writer";
$z[4]=Array("field","",439,478);
$z[4][4]['name']="source";
$z[5]=Array("field","",480,520);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",522,559);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B312Z-113L.png",561,644);
$z[7][4]['name']="litpic";

?>