{dede:field name='keywords'}站长之家, yinyue.com, 音乐域{/dede:field}
{dede:field name='description'}据whois资料显示，yinyue.com域名于昨日发生whois变更，目前所有人是4.CN ESCROW SERVICE，看来是由金名网中介的，据爆料，该域名为累主大神收购。{/dede:field}
{dede:field name='title'}音乐域名yinyue.com易主 交易价达7位数{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B312Z-113L.png{/dede:field}
