<?php
$z[0]=Array("field","站长之家, 百度站长平台",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","百度站长平台于5月29日在杭州举办了《移动搜索优化实用教程》专场培训，此外还展开了以“解网站移动化之痛”为主题的沙龙，分析了如何从技术层面解决网站移动化的疑问和痛",75,356);
$z[1][4]['name']="description";
$z[2]=Array("field","百度之夜：分享移动搜索优化策略及网站移动化痛点",358,465);
$z[2][4]['name']="title";
$z[3]=Array("field","",467,506);
$z[3][4]['name']="writer";
$z[4]=Array("field","",508,547);
$z[4][4]['name']="source";
$z[5]=Array("field","",549,589);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",591,628);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AW260-24P3.jpg",630,713);
$z[7][4]['name']="litpic";

?>