{dede:field name='keywords'}站长之家, 百度站长平台{/dede:field}
{dede:field name='description'}百度站长平台于5月29日在杭州举办了《移动搜索优化实用教程》专场培训，此外还展开了以“解网站移动化之痛”为主题的沙龙，分析了如何从技术层面解决网站移动化的疑问和痛{/dede:field}
{dede:field name='title'}百度之夜：分享移动搜索优化策略及网站移动化痛点{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AW260-24P3.jpg{/dede:field}
