<?php
$z[0]=Array("field","站长之家, 微店怎么开, 微",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近日，富士康旗下主营3C产品的微商项目“贝壳山”悄悄上线，华为、三星[微博]等手机产品已然上架。《每日经济新闻》记者从贝壳山运营团队内部获悉，贝壳山由深圳富士康独立",77,359);
$z[1][4]['name']="description";
$z[2]=Array("field","富士康进军微商 发动员工开微店卖3C",361,447);
$z[2][4]['name']="title";
$z[3]=Array("field","",449,488);
$z[3][4]['name']="writer";
$z[4]=Array("field","",490,529);
$z[4][4]['name']="source";
$z[5]=Array("field","",531,571);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",573,610);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B52030-19602.png",612,697);
$z[7][4]['name']="litpic";

?>