{dede:field name='keywords'}站长之家, 微店怎么开, 微{/dede:field}
{dede:field name='description'}近日，富士康旗下主营3C产品的微商项目“贝壳山”悄悄上线，华为、三星[微博]等手机产品已然上架。《每日经济新闻》记者从贝壳山运营团队内部获悉，贝壳山由深圳富士康独立{/dede:field}
{dede:field name='title'}富士康进军微商 发动员工开微店卖3C{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B52030-19602.png{/dede:field}
