<?php
$z[0]=Array("field","站长之家, 黑客攻击, 电脑",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","知名财经网站CNNMoney日前盘点了迄今为止史上最严重的10次黑客袭击事件，其中包括电脑病毒、信用卡盗窃、数据泄露以及尴尬备忘录泄露等。",77,308);
$z[1][4]['name']="description";
$z[2]=Array("field","",310,348);
$z[2][4]['name']="title";
$z[3]=Array("field","",350,389);
$z[3][4]['name']="writer";
$z[4]=Array("field","",391,430);
$z[4][4]['name']="source";
$z[5]=Array("field","",432,472);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",474,511);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B3V10-56213.jpg",513,597);
$z[7][4]['name']="litpic";

?>