{dede:field name='keywords'}站长之家, 黑客攻击, 电脑{/dede:field}
{dede:field name='description'}知名财经网站CNNMoney日前盘点了迄今为止史上最严重的10次黑客袭击事件，其中包括电脑病毒、信用卡盗窃、数据泄露以及尴尬备忘录泄露等。{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B3V10-56213.jpg{/dede:field}
