<?php
$z[0]=Array("field","站长之家, 网站建设, 网站",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","大家都知道，想要在网络上发展最好有个网站。可是，自己不会做网站就得找网络公司做，一个得上千，上万的。虽然也有便宜的，但是，网站感觉放在别人那里不放心，还是自己会",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","新手怎么学习网站建设？",363,434);
$z[2][4]['name']="title";
$z[3]=Array("field","",436,475);
$z[3][4]['name']="writer";
$z[4]=Array("field","",477,516);
$z[4][4]['name']="source";
$z[5]=Array("field","",518,558);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",560,597);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B1110-1I21.jpg",599,682);
$z[7][4]['name']="litpic";

?>