<?php
$z[0]=Array("field","站长之家, weixin.com, 域名交",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","4月中旬，“微信域名weixin.com被卖了3000万元的”的消息像一个深水炸弹一样，让域名圈瞬间炸开了锅，众人议论纷纷，从weixin.com的交易细节到买家究竟是不是腾讯，都被大",78,348);
$z[1][4]['name']="description";
$z[2]=Array("field","听“微信”域名weixin.com卖家队长讲故事",350,440);
$z[2][4]['name']="title";
$z[3]=Array("field","",442,481);
$z[3][4]['name']="writer";
$z[4]=Array("field","",483,522);
$z[4][4]['name']="source";
$z[5]=Array("field","",524,564);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",566,603);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425CC640-3G00.jpg",605,688);
$z[7][4]['name']="litpic";

?>