{dede:field name='keywords'}站长之家, weixin.com, 域名交{/dede:field}
{dede:field name='description'}4月中旬，“微信域名weixin.com被卖了3000万元的”的消息像一个深水炸弹一样，让域名圈瞬间炸开了锅，众人议论纷纷，从weixin.com的交易细节到买家究竟是不是腾讯，都被大{/dede:field}
{dede:field name='title'}听“微信”域名weixin.com卖家队长讲故事{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425CC640-3G00.jpg{/dede:field}
