<?php
$z[0]=Array("field","站长之家, 石墨文档, Goo",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","Google Docs 干掉了邮件里的文档附件，而石墨说，文档还可以有更轻、更优雅的分享方式。",74,235);
$z[1][4]['name']="description";
$z[2]=Array("field","石墨：我们共同写在云上的文档",237,317);
$z[2][4]['name']="title";
$z[3]=Array("field","",319,358);
$z[3][4]['name']="writer";
$z[4]=Array("field","",360,399);
$z[4][4]['name']="source";
$z[5]=Array("field","",401,441);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",443,480);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C3c20-33294.jpg",482,566);
$z[7][4]['name']="litpic";

?>