{dede:field name='keywords'}站长之家, 石墨文档, Goo{/dede:field}
{dede:field name='description'}Google Docs 干掉了邮件里的文档附件，而石墨说，文档还可以有更轻、更优雅的分享方式。{/dede:field}
{dede:field name='title'}石墨：我们共同写在云上的文档{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C3c20-33294.jpg{/dede:field}
