<?php
$z[0]=Array("field","站长之家, 域名投资, 域名",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","有的人手握普通域名，但却玩得一手好牌，也有的人手握资金，但却无从下手，以致好牌变烂牌。域名世界纷繁变化，各有各的成败，各有各的玩法，或许不一定都适合你，但却可以",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","经验大放送：米农分享域名投资的三W原则",363,456);
$z[2][4]['name']="title";
$z[3]=Array("field","",458,497);
$z[3][4]['name']="writer";
$z[4]=Array("field","",499,538);
$z[4][4]['name']="source";
$z[5]=Array("field","",540,580);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",582,619);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B64T0-2P58.jpg",621,704);
$z[7][4]['name']="litpic";

?>