<?php
$z[0]=Array("field","站长之家, 网站排名, 网站",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","对于每个站长而言，我们做一个网站最终的目的无疑都是希望网站可以在搜搜引擎中获取不错的排名，从而获得流量并且转换成收益，然而面对日渐衰退的SEO优化技术，很多靠此为",77,358);
$z[1][4]['name']="description";
$z[2]=Array("field","抓住四个时期 助力网站排名增长",360,441);
$z[2][4]['name']="title";
$z[3]=Array("field","",443,482);
$z[3][4]['name']="writer";
$z[4]=Array("field","",484,523);
$z[4][4]['name']="source";
$z[5]=Array("field","",525,565);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",567,604);
$z[6][4]['name']="body";
$z[7]=Array("field","",606,645);
$z[7][4]['name']="litpic";

?>