{dede:field name='keywords'}站长之家, 独角兽, 创业经{/dede:field}
{dede:field name='description'}家怎么计算你自己的初创企业的用户流失率呢？以每月丢失了多少个用户算？那抓不住重点，因为有大客户和小客户之分。{/dede:field}
{dede:field name='title'}市值110亿美元的独角兽是如何计算用户流失率的{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C2J10-19249.jpg{/dede:field}
