<?php
$z[0]=Array("field","站长之家, 独角兽, 创业经",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","家怎么计算你自己的初创企业的用户流失率呢？以每月丢失了多少个用户算？那抓不住重点，因为有大客户和小客户之分。",77,283);
$z[1][4]['name']="description";
$z[2]=Array("field","市值110亿美元的独角兽是如何计算用户流失率的",285,386);
$z[2][4]['name']="title";
$z[3]=Array("field","",388,427);
$z[3][4]['name']="writer";
$z[4]=Array("field","",429,468);
$z[4][4]['name']="source";
$z[5]=Array("field","",470,510);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",512,549);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C2J10-19249.jpg",551,635);
$z[7][4]['name']="litpic";

?>