{dede:field name='keywords'}站长之家, Uber创始人, Ka{/dede:field}
{dede:field name='description'}他在23岁时遇到了一个小麻烦：30多家媒体巨头联合起诉他的公司，要他赔偿2500亿美元。 你没看错，是2500“亿”。这钱能买下整个Facebook或阿里巴巴还有的剩。{/dede:field}
{dede:field name='title'}Uber创始人：23岁时负债2500亿美元 买下阿里巴巴还有剩{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C20420-15358.jpg{/dede:field}
