<?php
$z[0]=Array("field","站长之家, Uber创始人, Ka",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","他在23岁时遇到了一个小麻烦：30多家媒体巨头联合起诉他的公司，要他赔偿2500亿美元。 你没看错，是2500“亿”。这钱能买下整个Facebook或阿里巴巴还有的剩。",74,328);
$z[1][4]['name']="description";
$z[2]=Array("field","Uber创始人：23岁时负债2500亿美元 买下阿里巴巴还有剩",330,439);
$z[2][4]['name']="title";
$z[3]=Array("field","",441,480);
$z[3][4]['name']="writer";
$z[4]=Array("field","",482,521);
$z[4][4]['name']="source";
$z[5]=Array("field","",523,563);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",565,602);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C20420-15358.jpg",604,689);
$z[7][4]['name']="litpic";

?>