<div class="newsinclude">
<div class="news_pic fl"><a href="[field:arcurl/]" title="[field:title/]"><img src="[field:picname/]" width="345" height="220"></a></div>
<div class="news_txt fr"><h1><a href="[field:arcurl/]" title="[field:title/]">[field:title/]</a><br><span>UPTATED:[field:pubdate function=MyDate('Y/m/d',@me)/]</span></h1>
<p>[field:description/]...</p>
<a href="[field:arcurl/]">查看详情</a>
</div>
<div class="c"></div>
</div>