<?php
$z[0]=Array("field","站长之家, 博客赚钱, 博客",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","网络中赚钱的方法很多，比如CPA、CPC、CPM等都是一些传统和大众的赚钱方式，为什么我的网站值挂了百度联盟和淘宝客，百度联盟大家基本都知道。",77,316);
$z[1][4]['name']="description";
$z[2]=Array("field","4个适合博客赚钱的思路解析",318,393);
$z[2][4]['name']="title";
$z[3]=Array("field","",395,434);
$z[3][4]['name']="writer";
$z[4]=Array("field","",436,475);
$z[4][4]['name']="source";
$z[5]=Array("field","",477,517);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",519,556);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B453P-2c36.jpg",558,641);
$z[7][4]['name']="litpic";

?>