<?php
$z[0]=Array("field","{##SiteKeyword##}",0,58);
$z[0][4]['name']="keywords";
$z[1]=Array("field","【环球石材经典工程】紫御华府登顶亚洲精品住宅最高荣耀。4月24日，胡润百富发布《2015亚洲十大精工名宅》，以城市公园地产典范著称的紫御华府，在北京众多豪宅项目中脱颖而出，",60,348);
$z[1][4]['name']="description";
$z[2]=Array("field","北京紫御华府",350,406);
$z[2][4]['name']="title";
$z[3]=Array("field","",408,447);
$z[3][4]['name']="writer";
$z[4]=Array("field","",449,488);
$z[4][4]['name']="source";
$z[5]=Array("field","",490,527);
$z[5][4]['name']="body";
$z[6]=Array("field","",529,569);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",571,835);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c150614/14342504924Z-5a25.jpg",837,921);
$z[8][4]['name']="litpic";

?>