{dede:field name='keywords'}{##SiteKeyword##}{/dede:field}
{dede:field name='description'}【环球石材经典工程】紫御华府登顶亚洲精品住宅最高荣耀。4月24日，胡润百富发布《2015亚洲十大精工名宅》，以城市公园地产典范著称的紫御华府，在北京众多豪宅项目中脱颖而出，{/dede:field}
{dede:field name='title'}北京紫御华府{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='imgurls'}
{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}
{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/14342504924Z-5a25.jpg{/dede:field}
