<?php
$z[0]=Array("field","站长之家, 网站更新, 网站",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","大部分人都应该比较喜欢分析成功的案例，可惜啊，本人成功案例并不多，反倒是失败案例比较多，今天分享一个失败的案例，供小伙伴们参考，以免跟我一样犯同样的错误。标题已",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","我一天更新5篇文章 然而并没什么卵用",363,451);
$z[2][4]['name']="title";
$z[3]=Array("field","",453,492);
$z[3][4]['name']="writer";
$z[4]=Array("field","",494,533);
$z[4][4]['name']="source";
$z[5]=Array("field","",535,575);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",577,614);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B44240-19349.jpg",616,701);
$z[7][4]['name']="litpic";

?>