<?php
$z[0]=Array("field","站长之家, 网站分析工具",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","Mouse flow顾名思义,这是一个对用户鼠标行为进行追踪和分析工具。鼠标是用户与网站之间进行交互的主要工具，在网站分析中，我们经常需要对用户的鼠标行为进行追踪和分析，",75,352);
$z[1][4]['name']="description";
$z[2]=Array("field","网站分析和实时用户研究工具：Mouseflow",354,443);
$z[2][4]['name']="title";
$z[3]=Array("field","",445,484);
$z[3][4]['name']="writer";
$z[4]=Array("field","",486,525);
$z[4][4]['name']="source";
$z[5]=Array("field","",527,567);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",569,606);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AX2Z-32H7.png",608,690);
$z[7][4]['name']="litpic";

?>