<?php
$z[0]=Array("field","站长之家, 携程网全面瘫痪",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","携程数据库事件网上有各种说法。有说是数据库数据和备份数据被物理删除的。也有说是各个节点的业务代码被删除 现在重新在部署。也有说是误操作，导致业务不可用。尽管众说",78,360);
$z[1][4]['name']="description";
$z[2]=Array("field","携程网全面瘫痪！做一个大站必须得防黑客",362,457);
$z[2][4]['name']="title";
$z[3]=Array("field","",459,498);
$z[3][4]['name']="writer";
$z[4]=Array("field","",500,539);
$z[4][4]['name']="source";
$z[5]=Array("field","",541,581);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",583,620);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425CIH0-54362.jpg",622,705);
$z[7][4]['name']="litpic";

?>