{dede:field name='keywords'}站长之家, 携程网全面瘫痪{/dede:field}
{dede:field name='description'}携程数据库事件网上有各种说法。有说是数据库数据和备份数据被物理删除的。也有说是各个节点的业务代码被删除 现在重新在部署。也有说是误操作，导致业务不可用。尽管众说{/dede:field}
{dede:field name='title'}携程网全面瘫痪！做一个大站必须得防黑客{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425CIH0-54362.jpg{/dede:field}
