<?php
$z[0]=Array("field","站长之家, 网络时间协议",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","在企业环境下，如果企业不想为NTP流量打开防火墙，就有必要搭建一台内部的NTP服务器，让员工可以使用内部服务器，而不是公共NTP服务器。我们在本教程中将介绍如何将CentOS",75,350);
$z[1][4]['name']="description";
$z[2]=Array("field","如何在CentOS中搭建NTP服务器？",352,429);
$z[2][4]['name']="title";
$z[3]=Array("field","",431,470);
$z[3][4]['name']="writer";
$z[4]=Array("field","",472,511);
$z[4][4]['name']="source";
$z[5]=Array("field","",513,553);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",555,592);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C51T0-362R.png",594,677);
$z[7][4]['name']="litpic";

?>