{dede:field name='keywords'}站长之家, 网络时间协议{/dede:field}
{dede:field name='description'}在企业环境下，如果企业不想为NTP流量打开防火墙，就有必要搭建一台内部的NTP服务器，让员工可以使用内部服务器，而不是公共NTP服务器。我们在本教程中将介绍如何将CentOS{/dede:field}
{dede:field name='title'}如何在CentOS中搭建NTP服务器？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C51T0-362R.png{/dede:field}
