<?php
$z[0]=Array("field","站长之家, 微商, 微商怎么",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","微商警钟，希望对那些在朋友圈等平台大肆分享小广告或者各类财富洗脑的人一些警醒。走向微商正规需要更多企业和从业者进行自我规范。",77,307);
$z[1][4]['name']="description";
$z[2]=Array("field","浅析如何将微商这一新增渠道良性发展",309,398);
$z[2][4]['name']="title";
$z[3]=Array("field","",400,439);
$z[3][4]['name']="writer";
$z[4]=Array("field","",441,480);
$z[4][4]['name']="source";
$z[5]=Array("field","",482,522);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",524,561);
$z[6][4]['name']="body";
$z[7]=Array("field","",563,602);
$z[7][4]['name']="litpic";

?>