{dede:field name='keywords'}站长之家, 圆通速递, yto{/dede:field}
{dede:field name='description'}近日，圆通速递发布官微称正式启用了新域名ytoexpress.com，旧域名将并行使用至2015年12月31日。而这个被圆通总裁相峰称为“符合国内用户语言习惯、方便记忆”的域名却遭网{/dede:field}
{dede:field name='title'}圆通速递更换新域名遭打脸 网友：有点反人类{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AN110-2J08.png{/dede:field}
