<?php
$z[0]=Array("field","站长之家, 圆通速递, yto",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近日，圆通速递发布官微称正式启用了新域名ytoexpress.com，旧域名将并行使用至2015年12月31日。而这个被圆通总裁相峰称为“符合国内用户语言习惯、方便记忆”的域名却遭网",74,347);
$z[1][4]['name']="description";
$z[2]=Array("field","圆通速递更换新域名遭打脸 网友：有点反人类",349,448);
$z[2][4]['name']="title";
$z[3]=Array("field","",450,489);
$z[3][4]['name']="writer";
$z[4]=Array("field","",491,530);
$z[4][4]['name']="source";
$z[5]=Array("field","",532,572);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",574,611);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AN110-2J08.png",613,696);
$z[7][4]['name']="litpic";

?>