<?php
$z[0]=Array("field","站长之家, 怎么开微店, 微",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","微店是手机上的一款软件，也是当下最多人使用的手机开店应用，开店流程十分简单。下载安装，注册个号，只需要几分钟的时间就能开通属于自己的微店。微商可通过微信朋友圈、",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","教你怎么在手机上开微店",363,434);
$z[2][4]['name']="title";
$z[3]=Array("field","",436,475);
$z[3][4]['name']="writer";
$z[4]=Array("field","",477,516);
$z[4][4]['name']="source";
$z[5]=Array("field","",518,558);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",560,597);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AT620-12F5.png",599,682);
$z[7][4]['name']="litpic";

?>