{dede:field name='keywords'}站长之家, 怎么开微店, 微{/dede:field}
{dede:field name='description'}微店是手机上的一款软件，也是当下最多人使用的手机开店应用，开店流程十分简单。下载安装，注册个号，只需要几分钟的时间就能开通属于自己的微店。微商可通过微信朋友圈、{/dede:field}
{dede:field name='title'}教你怎么在手机上开微店{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AT620-12F5.png{/dede:field}
