{dede:noteinfo notename="产品展示" channelid="17" macthtype="string"
refurl="http://" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.umgg.biz/case/index.php?page=3{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="pic_arrange">{/dede:areastart}
    {dede:areaend}<div class="page">{/dede:areaend}
{/dede:listrule}
