<?php
$z[0]=Array("field","站长之家, Web安全, 网站安",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","国外科学家们对提供安全网站认证标志的十家知名安全服务商的认证服务进行了深入研究后发现，安全网站认证服务存在普遍的严重缺陷。",77,304);
$z[1][4]['name']="description";
$z[2]=Array("field","网站安全认证不靠谱？“安全网站”更容易遭黑",306,407);
$z[2][4]['name']="title";
$z[3]=Array("field","",409,448);
$z[3][4]['name']="writer";
$z[4]=Array("field","",450,489);
$z[4][4]['name']="source";
$z[5]=Array("field","",491,531);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",533,570);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C50X0-2LE.png",572,654);
$z[7][4]['name']="litpic";

?>