<?php
$z[0]=Array("field","站长之家, 微商怎么做, 微",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","通过以下三个方面对 微商进行全方位的疗伤，相 信只要微商能够做到以下三点那么微商的伤定会不治而愈。",77,264);
$z[1][4]['name']="description";
$z[2]=Array("field","我为微商疗伤",266,322);
$z[2][4]['name']="title";
$z[3]=Array("field","",324,363);
$z[3][4]['name']="writer";
$z[4]=Array("field","",365,404);
$z[4][4]['name']="source";
$z[5]=Array("field","",406,446);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",448,485);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AF260-1V06.jpg",487,570);
$z[7][4]['name']="litpic";

?>