<?php
$z[0]=Array("field","站长之家, wanda.com, bbbb.c",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","虽然国民老公鲜有涉及域名圈，但是每次一现身，就必然引起轰动，让我等小编欣喜不已。现在我们就来扒一扒这些年国民老公和域名的二三事吧。",74,313);
$z[1][4]['name']="description";
$z[2]=Array("field","米界八卦：国民老公王思聪和域名的二三事",315,410);
$z[2][4]['name']="title";
$z[3]=Array("field","",412,451);
$z[3][4]['name']="writer";
$z[4]=Array("field","",453,492);
$z[4][4]['name']="source";
$z[5]=Array("field","",494,534);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",536,573);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B014P-2H94.jpg",575,658);
$z[7][4]['name']="litpic";

?>