{dede:field name='keywords'}站长之家, wanda.com, bbbb.c{/dede:field}
{dede:field name='description'}虽然国民老公鲜有涉及域名圈，但是每次一现身，就必然引起轰动，让我等小编欣喜不已。现在我们就来扒一扒这些年国民老公和域名的二三事吧。{/dede:field}
{dede:field name='title'}米界八卦：国民老公王思聪和域名的二三事{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B014P-2H94.jpg{/dede:field}
