<?php
$z[0]=Array("field","站长之家, 微信运营, 微信",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","微信用户第一眼看到的是标题，如果标题没有吸引力的话，那么他们就不会点击，用户不点击，无论你的产品和服务是多么的棒，一切都是0……",77,311);
$z[1][4]['name']="description";
$z[2]=Array("field","微信运营：必须收藏的101条万能微信标题公式",313,411);
$z[2][4]['name']="title";
$z[3]=Array("field","",413,452);
$z[3][4]['name']="writer";
$z[4]=Array("field","",454,493);
$z[4][4]['name']="source";
$z[5]=Array("field","",495,535);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",537,574);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C52M0-4A13.jpg",576,659);
$z[7][4]['name']="litpic";

?>