<?php
$z[0]=Array("field","站长之家, 内容营销, 内容",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","很多时候，你会发现自己废寝忘食、通宵达旦地苦逼了一番，最后终于证明了自己是个傻逼，做出来的内容不是被人嘲笑就是被人鄙视。更惨的是，嘲笑和鄙视你的人就那么几个，还",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","什么样的内容才能让人尖叫？",363,440);
$z[2][4]['name']="title";
$z[3]=Array("field","",442,481);
$z[3][4]['name']="writer";
$z[4]=Array("field","",483,522);
$z[4][4]['name']="source";
$z[5]=Array("field","",524,564);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",566,603);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425A93460-1F06.jpg",605,689);
$z[7][4]['name']="litpic";

?>