<?php
$z[0]=Array("field","站长之家, 安全工具, 网络",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","什么是安全人员心中最佳的必备的安全工具？本文列出的工具均为产业分析师、安全从业者，以及行业协会成员的意见和推荐。这些安全专家指出，安全没有灵丹妙药，最好的策略就",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","做好网络安全工作的13大必备工具",363,445);
$z[2][4]['name']="title";
$z[3]=Array("field","",447,486);
$z[3][4]['name']="writer";
$z[4]=Array("field","",488,527);
$z[4][4]['name']="source";
$z[5]=Array("field","",529,569);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",571,608);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C49520-13011.png",610,695);
$z[7][4]['name']="litpic";

?>