<?php
$z[0]=Array("field","站长之家, 携程网瘫痪, 系",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","最近几天国内互联网圈接连出现停服事故，先是支付宝停服超过2小时，然后是携程停服超过8小时。一时间许多人大惊：原来大玩家们的运维水平这么出乎意料。",77,333);
$z[1][4]['name']="description";
$z[2]=Array("field","让自家系统瘫痪，这事我也干过",335,415);
$z[2][4]['name']="title";
$z[3]=Array("field","",417,456);
$z[3][4]['name']="writer";
$z[4]=Array("field","",458,497);
$z[4][4]['name']="source";
$z[5]=Array("field","",499,539);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",541,578);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425A64F-3X93.jpg",580,662);
$z[7][4]['name']="litpic";

?>