{dede:field name='keywords'}站长之家, 携程网瘫痪, 系{/dede:field}
{dede:field name='description'}最近几天国内互联网圈接连出现停服事故，先是支付宝停服超过2小时，然后是携程停服超过8小时。一时间许多人大惊：原来大玩家们的运维水平这么出乎意料。{/dede:field}
{dede:field name='title'}让自家系统瘫痪，这事我也干过{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425A64F-3X93.jpg{/dede:field}
