<?php
$z[0]=Array("field","站长之家, 阿里模式, 产品",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","一个已经基本掌握技巧的运营，依旧受制于产品，唯“产品”至上观，不懂利用运营优势去倒逼产品设计。产品重要吗？当然重要，但是运营不能因此妄自菲薄，丧失对全局的把控，",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","我在阿里做运营（三）：八一八那些运营经典误区",363,467);
$z[2][4]['name']="title";
$z[3]=Array("field","",469,508);
$z[3][4]['name']="writer";
$z[4]=Array("field","",510,549);
$z[4][4]['name']="source";
$z[5]=Array("field","",551,591);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",593,630);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425Bb010-43a3.png",632,715);
$z[7][4]['name']="litpic";

?>