{dede:field name='keywords'}2015厦门国际石材展——环{/dede:field}
{dede:field name='description'}2015厦门国际石材展——环球石材邀您共赏【石材·灵动的炫律】{/dede:field}
{dede:field name='title'}2015厦门国际石材展——环球石材邀您共赏【石材·灵动的炫律】{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/1434245b43F-34629.jpg{/dede:field}
