<?php
$z[0]=Array("field","站长之家, 网站运营, 网站",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","系统性的运营网站，不仅可以大大提高工作效率，做到事半功倍，关键是可以减少犯错的机会，让网站运营更加专业化~",77,278);
$z[1][4]['name']="description";
$z[2]=Array("field","​【读图】网站运营流程体系",280,357);
$z[2][4]['name']="title";
$z[3]=Array("field","",359,398);
$z[3][4]['name']="writer";
$z[4]=Array("field","",400,439);
$z[4][4]['name']="source";
$z[5]=Array("field","",441,481);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",483,520);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C53510-5A08.png",522,606);
$z[7][4]['name']="litpic";

?>