{dede:field name='keywords'}站长之家, 草根站长, 中国{/dede:field}
{dede:field name='description'}多年以前站长很热的时候，资讯网站、知识网站满天飞，那时候SEO就被站长神话了，认为做好了SEO，网站就离赚钱不远了，于是互联网上流传一种说法，要IP、要流量，流量为王。{/dede:field}
{dede:field name='title'}站长时代衰落 下一个平民时代是网络营销时代？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
