<?php
$z[0]=Array("field","站长之家, 草根站长, 中国",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","多年以前站长很热的时候，资讯网站、知识网站满天飞，那时候SEO就被站长神话了，认为做好了SEO，网站就离赚钱不远了，于是互联网上流传一种说法，要IP、要流量，流量为王。",77,357);
$z[1][4]['name']="description";
$z[2]=Array("field","站长时代衰落 下一个平民时代是网络营销时代？",359,461);
$z[2][4]['name']="title";
$z[3]=Array("field","",463,502);
$z[3][4]['name']="writer";
$z[4]=Array("field","",504,543);
$z[4][4]['name']="source";
$z[5]=Array("field","",545,585);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",587,624);
$z[6][4]['name']="body";
$z[7]=Array("field","",626,665);
$z[7][4]['name']="litpic";

?>