<?php
$z[0]=Array("field","站长之家, 网站运营, 产品",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","入行互联网后，做了2年杂役，3年运营，期间风云变幻过网编、产品策划、销售联盟、SEO、网推、网站分析等职务。自从职称变为运营经理后，我便每日敲木参“禅”：运营经理究",77,357);
$z[1][4]['name']="description";
$z[2]=Array("field","网站运营经理的变迁史",359,427);
$z[2][4]['name']="title";
$z[3]=Array("field","",429,468);
$z[3][4]['name']="writer";
$z[4]=Array("field","",470,509);
$z[4][4]['name']="source";
$z[5]=Array("field","",511,551);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",553,590);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AGO0-31I4.jpg",592,674);
$z[7][4]['name']="litpic";

?>