{dede:field name='keywords'}站长之家, 域名交易, 域名{/dede:field}
{dede:field name='description'}资深评论人 @康国平 发微博称找半天才找到360奇酷网（qikoo.com），并艾特周鸿祎“你家域名太奇葩”，老周不仅“虚心接受”，还指责为何相关人员没有将域名切换到qiku.com{/dede:field}
{dede:field name='title'}周鸿祎谈奇酷域名：“我们”真他妈的有钱{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AM2F-1b43.jpg{/dede:field}
