<?php
$z[0]=Array("field","站长之家, 域名交易, 域名",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","资深评论人 @康国平 发微博称找半天才找到360奇酷网（qikoo.com），并艾特周鸿祎“你家域名太奇葩”，老周不仅“虚心接受”，还指责为何相关人员没有将域名切换到qiku.com",77,348);
$z[1][4]['name']="description";
$z[2]=Array("field","周鸿祎谈奇酷域名：“我们”真他妈的有钱",350,445);
$z[2][4]['name']="title";
$z[3]=Array("field","",447,486);
$z[3][4]['name']="writer";
$z[4]=Array("field","",488,527);
$z[4][4]['name']="source";
$z[5]=Array("field","",529,569);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",571,608);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AM2F-1b43.jpg",610,692);
$z[7][4]['name']="litpic";

?>