<?php
$z[0]=Array("field","站长之家, 网站备案, 网站",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","网站备案对于广大IT从业者或者草根站长来说并不陌生，我对于网站备案这个制度持中立态度：一方面，网站备案有利于规范互联网环境;另一方面，繁琐的备案流程、苛刻的审核条",77,358);
$z[1][4]['name']="description";
$z[2]=Array("field","个人备案：原主体下其他网站内容不合格解决方法",360,464);
$z[2][4]['name']="title";
$z[3]=Array("field","",466,505);
$z[3][4]['name']="writer";
$z[4]=Array("field","",507,546);
$z[4][4]['name']="source";
$z[5]=Array("field","",548,588);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",590,627);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BQD0-2W03.jpg",629,711);
$z[7][4]['name']="litpic";

?>