<?php
$z[0]=Array("field","站长之家, 外链建设, SEO",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","SEOer每天的工作大都在不停的写作+外链，而且由此维护而产生的效果却是越来越不明显。为什么每天都在更新却没有任何效果呢？因为我们已经走进了工作的盲区。",74,334);
$z[1][4]['name']="description";
$z[2]=Array("field","SEOer怎样走出优化盲区？",336,406);
$z[2][4]['name']="title";
$z[3]=Array("field","",408,447);
$z[3][4]['name']="writer";
$z[4]=Array("field","",449,488);
$z[4][4]['name']="source";
$z[5]=Array("field","",490,530);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",532,569);
$z[6][4]['name']="body";
$z[7]=Array("field","",571,610);
$z[7][4]['name']="litpic";

?>