<?php
$z[0]=Array("field","站长之家, 手机浏览器,",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","本文对国内市场份额前三名的UC手机浏览器、QQ手机浏览器、百度手机浏览器进行逐一对比。",73,238);
$z[1][4]['name']="description";
$z[2]=Array("field","三大主流手机浏览器对比：哪个最安全？",240,332);
$z[2][4]['name']="title";
$z[3]=Array("field","",334,373);
$z[3][4]['name']="writer";
$z[4]=Array("field","",375,414);
$z[4][4]['name']="source";
$z[5]=Array("field","",416,456);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",458,495);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B4A0-3T58.jpg",497,579);
$z[7][4]['name']="litpic";

?>