<?php
$z[0]=Array("field","站长之家, 360.wang, 域名交",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","域名360.wang，从面上看就知道和“奇虎360”相关，年前交易的亿元域名360.com余震未减，3数字域名价值在360.com的影响下水涨船高。此次360.wang以49万元结拍，品牌效应可见",76,342);
$z[1][4]['name']="description";
$z[2]=Array("field","域名360.wang以49万元结拍！老周 你拍的？",344,435);
$z[2][4]['name']="title";
$z[3]=Array("field","",437,476);
$z[3][4]['name']="writer";
$z[4]=Array("field","",478,517);
$z[4][4]['name']="source";
$z[5]=Array("field","",519,559);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",561,598);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AQ640-55F3.jpg",600,683);
$z[7][4]['name']="litpic";

?>