{dede:field name='keywords'}站长之家, 360.wang, 域名交{/dede:field}
{dede:field name='description'}域名360.wang，从面上看就知道和“奇虎360”相关，年前交易的亿元域名360.com余震未减，3数字域名价值在360.com的影响下水涨船高。此次360.wang以49万元结拍，品牌效应可见{/dede:field}
{dede:field name='title'}域名360.wang以49万元结拍！老周 你拍的？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AQ640-55F3.jpg{/dede:field}
