<?php
$z[0]=Array("field","站长之家, 阿里模式, 产品",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","我是一个即将离开阿里的运营妹子，在阿里做运营三年有余，离职是我久经思考的决定，平时忙成狗，做惯了嘻嘻哈哈的段子手，这会儿正经起来掏心窝，还真有点不适应。",77,349);
$z[1][4]['name']="description";
$z[2]=Array("field","我在阿里做运营（二）：离职前的感悟",351,440);
$z[2][4]['name']="title";
$z[3]=Array("field","",442,481);
$z[3][4]['name']="writer";
$z[4]=Array("field","",483,522);
$z[4][4]['name']="source";
$z[5]=Array("field","",524,564);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",566,603);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C02a0-12F0.jpg",605,688);
$z[7][4]['name']="litpic";

?>