{dede:field name='keywords'}站长之家, 阿里模式, 产品{/dede:field}
{dede:field name='description'}我是一个即将离开阿里的运营妹子，在阿里做运营三年有余，离职是我久经思考的决定，平时忙成狗，做惯了嘻嘻哈哈的段子手，这会儿正经起来掏心窝，还真有点不适应。{/dede:field}
{dede:field name='title'}我在阿里做运营（二）：离职前的感悟{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C02a0-12F0.jpg{/dede:field}
