{dede:noteinfo notename="建站经验" channelid="1" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://www.chinaz.com/web/exp/(*).shtml"
startid="1" endid="5" addv="1" urlrule="area" musthas="2015"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.chinaz.com/start/{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="newsListBar current">{/dede:areastart}
    {dede:areaend}<div class="pagecon tc clearfix ptb25">{/dede:areaend}
{/dede:listrule}
