{dede:field name='keywords'}站长之家, 移动站点收录{/dede:field}
{dede:field name='description'}负责PC、移动站点适配的SEOer有没有被老板责问“为什么适配工作做了这么久，移动收录量怎么还这么低”？同行在一起有没有讨论过“百度是不是不待见PC移动适配这种方式？所{/dede:field}
{dede:field name='title'}VIP大讲堂：为何适配移动站点收录量如此少？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B4R10-43649.jpg{/dede:field}
