<?php
$z[0]=Array("field","站长之家, 移动站点收录",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","负责PC、移动站点适配的SEOer有没有被老板责问“为什么适配工作做了这么久，移动收录量怎么还这么低”？同行在一起有没有讨论过“百度是不是不待见PC移动适配这种方式？所",75,353);
$z[1][4]['name']="description";
$z[2]=Array("field","VIP大讲堂：为何适配移动站点收录量如此少？",355,453);
$z[2][4]['name']="title";
$z[3]=Array("field","",455,494);
$z[3][4]['name']="writer";
$z[4]=Array("field","",496,535);
$z[4][4]['name']="source";
$z[5]=Array("field","",537,577);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",579,616);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B4R10-43649.jpg",618,702);
$z[7][4]['name']="litpic";

?>