{dede:field name='keywords'}站长之家, 王思聪, bbbb.c{/dede:field}
{dede:field name='description'}国民老公王思聪买了个域名的消息，让整个微博朋友圈都炸开了锅，从昨天到今天，“王思聪买4B域名”、“王思聪bbbb.com”的话题热度一直居高不下，就连周鸿祎都受此影响，考{/dede:field}
{dede:field name='title'}王思聪买域名bbbb.com番外：周鸿祎想买下bb.com？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B1R20-4M45.png{/dede:field}
