<?php
$z[0]=Array("field","站长之家, 王思聪, bbbb.c",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","国民老公王思聪买了个域名的消息，让整个微博朋友圈都炸开了锅，从昨天到今天，“王思聪买4B域名”、“王思聪bbbb.com”的话题热度一直居高不下，就连周鸿祎都受此影响，考",74,353);
$z[1][4]['name']="description";
$z[2]=Array("field","王思聪买域名bbbb.com番外：周鸿祎想买下bb.com？",355,455);
$z[2][4]['name']="title";
$z[3]=Array("field","",457,496);
$z[3][4]['name']="writer";
$z[4]=Array("field","",498,537);
$z[4][4]['name']="source";
$z[5]=Array("field","",539,579);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",581,618);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B1R20-4M45.png",620,703);
$z[7][4]['name']="litpic";

?>