{dede:field name='keywords'}站长之家, HolaVPN, VPN服务{/dede:field}
{dede:field name='description'}上周，一个名叫Adios Hola（Adios西班牙语中意为“再见”，Hola意思相当于英语中的Hello）的研究团队发布一份安全报告，指出在Hola VPN中存在的漏洞，可导致信息泄露、任意{/dede:field}
{dede:field name='title'}Hola VPN 给出修复方案 但问题仍在{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B14130-2HR.jpg{/dede:field}
