<?php
$z[0]=Array("field","站长之家, HolaVPN, VPN服务",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","上周，一个名叫Adios Hola（Adios西班牙语中意为“再见”，Hola意思相当于英语中的Hello）的研究团队发布一份安全报告，指出在Hola VPN中存在的漏洞，可导致信息泄露、任意",75,343);
$z[1][4]['name']="description";
$z[2]=Array("field","Hola VPN 给出修复方案 但问题仍在",345,426);
$z[2][4]['name']="title";
$z[3]=Array("field","",428,467);
$z[3][4]['name']="writer";
$z[4]=Array("field","",469,508);
$z[4][4]['name']="source";
$z[5]=Array("field","",510,550);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",552,589);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B14130-2HR.jpg",591,674);
$z[7][4]['name']="litpic";

?>