<?php
$z[0]=Array("field","{##SiteKeyword##}",0,58);
$z[0][4]['name']="keywords";
$z[1]=Array("field","{##SiteDescription##}",60,125);
$z[1][4]['name']="description";
$z[2]=Array("field","2015年厦门石材展 | 每一年，都有不可错过的美景",127,229);
$z[2][4]['name']="title";
$z[3]=Array("field","",231,270);
$z[3][4]['name']="writer";
$z[4]=Array("field","",272,311);
$z[4][4]['name']="source";
$z[5]=Array("field","",313,350);
$z[5][4]['name']="body";
$z[6]=Array("field","",352,392);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c150614/1434245b4H0-49191.jpg",394,478);
$z[7][4]['name']="litpic";

?>