{dede:field name='keywords'}{##SiteKeyword##}{/dede:field}
{dede:field name='description'}{##SiteDescription##}{/dede:field}
{dede:field name='title'}2015年厦门石材展 | 每一年，都有不可错过的美景{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/1434245b4H0-49191.jpg{/dede:field}
