{dede:field name='keywords'}站长之家, 百度移动搜索{/dede:field}
{dede:field name='description'}近日百度宣布收购日本原生态广告公司popIn的控股权，收购完成后，百度广告平台将会采用popIn自创的READ技术和内容推荐技术进一步提升在原生广告领域的技术能力，使其在移动{/dede:field}
{dede:field name='title'}移动为先！百度国际化的价值新蓝图{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425BL910-560F.jpg{/dede:field}
