<?php
$z[0]=Array("field","站长之家, 百度移动搜索",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近日百度宣布收购日本原生态广告公司popIn的控股权，收购完成后，百度广告平台将会采用popIn自创的READ技术和内容推荐技术进一步提升在原生广告领域的技术能力，使其在移动",75,352);
$z[1][4]['name']="description";
$z[2]=Array("field","移动为先！百度国际化的价值新蓝图",354,440);
$z[2][4]['name']="title";
$z[3]=Array("field","",442,481);
$z[3][4]['name']="writer";
$z[4]=Array("field","",483,522);
$z[4][4]['name']="source";
$z[5]=Array("field","",524,564);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",566,603);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BL910-560F.jpg",605,688);
$z[7][4]['name']="litpic";

?>