<?php
$z[0]=Array("field","站长之家, 淘宝运营, 用户",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","现在很多人 老是在说淘宝难做，认真想想为什么难做了？淘宝把本来畅通的流量卡死了，跟收费站一样，一段段的限行收费，卖家那么多，淘宝日均4千万的UV分到每个人头上，汤都",77,359);
$z[1][4]['name']="description";
$z[2]=Array("field","淘宝运营必看！如何提升用户的重复购买次数？",361,462);
$z[2][4]['name']="title";
$z[3]=Array("field","",464,503);
$z[3][4]['name']="writer";
$z[4]=Array("field","",505,544);
$z[4][4]['name']="source";
$z[5]=Array("field","",546,586);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",588,625);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B35N0-33353.jpg",627,711);
$z[7][4]['name']="litpic";

?>