<?php
$z[0]=Array("field","站长之家, 谷歌优化, Opt",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","在域名的问题上，谷歌从来都不会“心慈手软”。据外媒近日消息称，谷歌以“容易引起混淆”为由，就“OptimizeGoogle.com”域名向美国国家仲裁论坛（The National Arbitrati",74,338);
$z[1][4]['name']="description";
$z[2]=Array("field","谷歌为“OptimizeGoogle.com”域名申请域名仲裁",340,435);
$z[2][4]['name']="title";
$z[3]=Array("field","",437,476);
$z[3][4]['name']="writer";
$z[4]=Array("field","",478,517);
$z[4][4]['name']="source";
$z[5]=Array("field","",519,559);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",561,598);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B53X0-24206.png",600,684);
$z[7][4]['name']="litpic";

?>