{dede:field name='keywords'}站长之家, 网站移动化, 百{/dede:field}
{dede:field name='description'}5月29日，百度站长平台在杭州举办了以“网站移动化之痛”为主题的沙龙。百度移动搜索技术总监王昊在《移动搜索下新机遇新挑战》演讲中介绍了百度移动搜索的发展趋势、用户{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425A95440-364H.png{/dede:field}
