<?php
$z[0]=Array("field","站长之家, 网站移动化, 百",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","5月29日，百度站长平台在杭州举办了以“网站移动化之痛”为主题的沙龙。百度移动搜索技术总监王昊在《移动搜索下新机遇新挑战》演讲中介绍了百度移动搜索的发展趋势、用户",77,358);
$z[1][4]['name']="description";
$z[2]=Array("field","",360,398);
$z[2][4]['name']="title";
$z[3]=Array("field","",400,439);
$z[3][4]['name']="writer";
$z[4]=Array("field","",441,480);
$z[4][4]['name']="source";
$z[5]=Array("field","",482,522);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",524,561);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425A95440-364H.png",563,647);
$z[7][4]['name']="litpic";

?>