<?php
$z[0]=Array("field","站长之家, 文章写作, 内容",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","什么叫好文案？刘禹含认为是能够强烈引发受众某种情感的文章，能够直击人心。",77,229);
$z[1][4]['name']="description";
$z[2]=Array("field","怎么写出直击人心的好文案？",231,308);
$z[2][4]['name']="title";
$z[3]=Array("field","",310,349);
$z[3][4]['name']="writer";
$z[4]=Array("field","",351,390);
$z[4][4]['name']="source";
$z[5]=Array("field","",392,432);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",434,471);
$z[6][4]['name']="body";
$z[7]=Array("field","",473,512);
$z[7][4]['name']="litpic";

?>