<?php
$z[0]=Array("field","{##SiteKeyword##}",0,58);
$z[0][4]['name']="keywords";
$z[1]=Array("field","{##SiteDescription##}",60,125);
$z[1][4]['name']="description";
$z[2]=Array("field","太原得一·理想国",127,188);
$z[2][4]['name']="title";
$z[3]=Array("field","",190,229);
$z[3][4]['name']="writer";
$z[4]=Array("field","",231,270);
$z[4][4]['name']="source";
$z[5]=Array("field","",272,309);
$z[5][4]['name']="body";
$z[6]=Array("field","",311,351);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",353,617);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c150614/1434250494D0-110Y.jpg",619,703);
$z[8][4]['name']="litpic";

?>