{dede:field name='keywords'}站长之家, GoDaddy, 域名注册{/dede:field}
{dede:field name='description'}在GODADDY 公司任命Blake Irving为其新任CEO时，Elissa Murphy是Irving最先想到邀请加入的为数不多的人之一。Irving曾与Murphy在微软和雅虎共职，那时Murphy是工程部副经理{/dede:field}
{dede:field name='title'}GoDaddy 和你想的不一样{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425A625F-252U.png{/dede:field}
