<?php
$z[0]=Array("field","站长之家, GoDaddy, 域名注册",0,76);
$z[0][4]['name']="keywords";
$z[1]=Array("field","在GODADDY 公司任命Blake Irving为其新任CEO时，Elissa Murphy是Irving最先想到邀请加入的为数不多的人之一。Irving曾与Murphy在微软和雅虎共职，那时Murphy是工程部副经理",78,332);
$z[1][4]['name']="description";
$z[2]=Array("field","GoDaddy 和你想的不一样",334,401);
$z[2][4]['name']="title";
$z[3]=Array("field","",403,442);
$z[3][4]['name']="writer";
$z[4]=Array("field","",444,483);
$z[4][4]['name']="source";
$z[5]=Array("field","",485,525);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",527,564);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425A625F-252U.png",566,649);
$z[7][4]['name']="litpic";

?>