<?php
$z[0]=Array("global","",181,207);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","",248,270);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",310,361);
$z[2][4]['name']="description";
$z[2][4]['function']="html2text(@me)";
$z[3]=Array("php","\r\npasterTempletDiy(\"wap/head.htm\");\r\n",530,588);
$z[4]=Array("field","",650,672);
$z[4][4]['name']="position";
$z[5]=Array("field","",760,779);
$z[5][4]['name']="title";
$z[6]=Array("arclist","\r\n			[field:ylcpjs/]\r\n			",813,907);
$z[6][4]['channelid']="1";
$z[6][4]['addfields']="ylcpjs,ylgylc";
$z[7]=Array("field","",1071,1091);
$z[7][4]['name']="litpic";
$z[8]=Array("field","",1215,1233);
$z[8][4]['name']="body";
$z[9]=Array("php","\r\npasterTempletDiy(\"wap/footer.htm\");\r\n",1288,1348);

?>