<?php
$z[0]=Array("field","",109,128);
$z[0][4]['name']="title";
$z[1]=Array("global","",129,155);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",196,225);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",265,323);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",709,744);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1175,1204);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n",1212,1389);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[7]=Array("field","",1642,1661);
$z[7][4]['name']="title";
$z[8]=Array("productimagelist"," \r\n<li><a href=\"[field:imgsrc/]\"><img src=\"[field:imgsrc/]\" width=\"157\" height=\"107\" alt=\"[field:text/]\"/></a></li>							\r\n",1881,2052);
$z[9]=Array("field","",2159,2177);
$z[9][4]['name']="body";
$z[10]=Array("include","",2277,2314);
$z[10][4]['filename']="footer.htm";

?>