<?php
$z[0]=Array("field","",109,128);
$z[0][4]['name']="title";
$z[1]=Array("global","",129,155);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",196,225);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",265,323);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",576,611);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",826,849);
$z[5][4]['name']="typename";
$z[6]=Array("field","",1002,1031);
$z[6][4]['name']="position";
$z[7]=Array("channel","\r\n<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n",1039,1216);
$z[7][4]['type']="son";
$z[7][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[8]=Array("field","",1378,1397);
$z[8][4]['name']="title";
$z[9]=Array("field","",1421,1477);
$z[9][4]['name']="pubdate";
$z[9][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[10]=Array("field","",1535,1562);
$z[10][4]['name']="phpurl";
$z[11]=Array("field","",1586,1609);
$z[11][4]['name']="id";
$z[12]=Array("field","",1614,1638);
$z[12][4]['name']="mid";
$z[13]=Array("field","",1759,1777);
$z[13][4]['name']="body";
$z[14]=Array("include","",1881,1918);
$z[14][4]['filename']="footer.htm";

?>