<?php
$z[0]=Array("field","站长之家, 谷歌移动搜索",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近日，谷歌发布官方博客称，将把iOS应用并入搜索引擎结果页中，即在未来的谷歌搜索结果页中会显示相关的iOS应用信息（注：针对iOS设备用户）。这也是谷歌继Android应用之后",75,351);
$z[1][4]['name']="description";
$z[2]=Array("field","继安卓后 谷歌将在移动搜索中展示iOS应用信息",353,452);
$z[2][4]['name']="title";
$z[3]=Array("field","",454,493);
$z[3][4]['name']="writer";
$z[4]=Array("field","",495,534);
$z[4][4]['name']="source";
$z[5]=Array("field","",536,576);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",578,615);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C62310-3T19.jpg",617,701);
$z[7][4]['name']="litpic";

?>