{dede:field name='keywords'}站长之家, 谷歌移动搜索{/dede:field}
{dede:field name='description'}近日，谷歌发布官方博客称，将把iOS应用并入搜索引擎结果页中，即在未来的谷歌搜索结果页中会显示相关的iOS应用信息（注：针对iOS设备用户）。这也是谷歌继Android应用之后{/dede:field}
{dede:field name='title'}继安卓后 谷歌将在移动搜索中展示iOS应用信息{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C62310-3T19.jpg{/dede:field}
