<?php
$z[0]=Array("field","站长之家, 自媒体营销, 内",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","经历了三年执行力全无，行尸走肉般的三年之后，我决定再一次挑战自己！而这一次我的方向是移动互联网！",77,265);
$z[1][4]['name']="description";
$z[2]=Array("field","自媒体人的行销法则",267,332);
$z[2][4]['name']="title";
$z[3]=Array("field","",334,373);
$z[3][4]['name']="writer";
$z[4]=Array("field","",375,414);
$z[4][4]['name']="source";
$z[5]=Array("field","",416,456);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",458,495);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B04630-49205.jpg",497,582);
$z[7][4]['name']="litpic";

?>