{dede:field name='keywords'}站长之家, 自媒体营销, 内{/dede:field}
{dede:field name='description'}经历了三年执行力全无，行尸走肉般的三年之后，我决定再一次挑战自己！而这一次我的方向是移动互联网！{/dede:field}
{dede:field name='title'}自媒体人的行销法则{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B04630-49205.jpg{/dede:field}
