{dede:field name='keywords'}站长之家, 罗斯柴尔德, 罗{/dede:field}
{dede:field name='description'}罗斯柴尔德之所以能够“左强东右马云”，靠得自然是自己的雄厚实力和在金融界根深蒂固的关系。所以说，互联网公司虽然看上去个个都“碉堡”，但他们其实无法离开像罗斯柴尔{/dede:field}
{dede:field name='title'}罗斯柴尔德家族的投资秘史：左手抓刘强东，右手牵马云{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C14920-21b3.jpg{/dede:field}
