<?php
$z[0]=Array("field","站长之家, 罗斯柴尔德, 罗",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","罗斯柴尔德之所以能够“左强东右马云”，靠得自然是自己的雄厚实力和在金融界根深蒂固的关系。所以说，互联网公司虽然看上去个个都“碉堡”，但他们其实无法离开像罗斯柴尔",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","罗斯柴尔德家族的投资秘史：左手抓刘强东，右手牵马云",363,476);
$z[2][4]['name']="title";
$z[3]=Array("field","",478,517);
$z[3][4]['name']="writer";
$z[4]=Array("field","",519,558);
$z[4][4]['name']="source";
$z[5]=Array("field","",560,600);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",602,639);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C14920-21b3.jpg",641,725);
$z[7][4]['name']="litpic";

?>