<?php
$z[0]=Array("field","站长之家, 事件营销, 产品",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","此次的支付宝和携程的事件，已经快过去一周了，作为一家创业公司的PR，我来讲讲我们是如何通过此次事件获得百万关注的事情。你可能注意到了，我用的人称是“我们”，的确，",77,360);
$z[1][4]['name']="description";
$z[2]=Array("field","PR实战：借力携程事件不花钱获得百万关注",362,456);
$z[2][4]['name']="title";
$z[3]=Array("field","",458,497);
$z[3][4]['name']="writer";
$z[4]=Array("field","",499,538);
$z[4][4]['name']="source";
$z[5]=Array("field","",540,580);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",582,619);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425Aa1Z-56419.jpg",621,704);
$z[7][4]['name']="litpic";

?>