{dede:field name='keywords'}站长之家, 事件营销, 产品{/dede:field}
{dede:field name='description'}此次的支付宝和携程的事件，已经快过去一周了，作为一家创业公司的PR，我来讲讲我们是如何通过此次事件获得百万关注的事情。你可能注意到了，我用的人称是“我们”，的确，{/dede:field}
{dede:field name='title'}PR实战：借力携程事件不花钱获得百万关注{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425Aa1Z-56419.jpg{/dede:field}
