{dede:field name='keywords'}站长之家, 自媒体, 自媒体{/dede:field}
{dede:field name='description'}随着前几批自媒体人开始盈利，并呈现出高增长态势，自媒体概念在市场中的热度也快速升温。越来越多的参与者加入到自媒体大军中来，除了一个个独立的自媒体人之外，其中还包{/dede:field}
{dede:field name='title'}自媒体的传播力量之生死法则{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425A94B0-22204.jpg{/dede:field}
