<?php
$z[0]=Array("field","站长之家, 自媒体, 自媒体",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","随着前几批自媒体人开始盈利，并呈现出高增长态势，自媒体概念在市场中的热度也快速升温。越来越多的参与者加入到自媒体大军中来，除了一个个独立的自媒体人之外，其中还包",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","自媒体的传播力量之生死法则",363,440);
$z[2][4]['name']="title";
$z[3]=Array("field","",442,481);
$z[3][4]['name']="writer";
$z[4]=Array("field","",483,522);
$z[4][4]['name']="source";
$z[5]=Array("field","",524,564);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",566,603);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425A94B0-22204.jpg",605,689);
$z[7][4]['name']="litpic";

?>