{dede:field name='keywords'}站长之家, 微信营销, 微信{/dede:field}
{dede:field name='description'}在国内，美式甜品品牌基本没有。从商业角度讲，这其实是市场的一个空缺。所以我决定做一个美式甜品文化在中国的传播者，将品牌从美国引入中国。{/dede:field}
{dede:field name='title'}浙大美女高考状元裸辞创业：微信卖蛋糕转化率20%{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C15Q0-3Q94.png{/dede:field}
