<?php
$z[0]=Array("field","站长之家, 微信营销, 微信",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","在国内，美式甜品品牌基本没有。从商业角度讲，这其实是市场的一个空缺。所以我决定做一个美式甜品文化在中国的传播者，将品牌从美国引入中国。",77,322);
$z[1][4]['name']="description";
$z[2]=Array("field","浙大美女高考状元裸辞创业：微信卖蛋糕转化率20%",324,428);
$z[2][4]['name']="title";
$z[3]=Array("field","",430,469);
$z[3][4]['name']="writer";
$z[4]=Array("field","",471,510);
$z[4][4]['name']="source";
$z[5]=Array("field","",512,552);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",554,591);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C15Q0-3Q94.png",593,676);
$z[7][4]['name']="litpic";

?>