<?php
$z[0]=Array("field","站长之家, 西安, 互联网创",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","西安，经历了13个朝代的沉淀，它的古典早已经深入骨髓。这座充满历史感的城市告诉人们，有一种美是需要历经沧桑才可以达到的。现如今，互联网的大潮从南向北而来，不可避免",77,360);
$z[1][4]['name']="description";
$z[2]=Array("field","古城西安互联网创业公司大盘点",362,442);
$z[2][4]['name']="title";
$z[3]=Array("field","",444,483);
$z[3][4]['name']="writer";
$z[4]=Array("field","",485,524);
$z[4][4]['name']="source";
$z[5]=Array("field","",526,566);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",568,605);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C22560-36112.jpg",607,692);
$z[7][4]['name']="litpic";

?>