{dede:field name='keywords'}站长之家, 西安, 互联网创{/dede:field}
{dede:field name='description'}西安，经历了13个朝代的沉淀，它的古典早已经深入骨髓。这座充满历史感的城市告诉人们，有一种美是需要历经沧桑才可以达到的。现如今，互联网的大潮从南向北而来，不可避免{/dede:field}
{dede:field name='title'}古城西安互联网创业公司大盘点{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C22560-36112.jpg{/dede:field}
