<?php
$z[0]=Array("field","站长之家, 网络推广, 盈利",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","都是做同样的事情，不同的人通过不同的思维就会产生不一样的结果。同样是逛论坛发帖，有的人是为了娱乐陶冶生活情操，而有的人却能利用论坛发帖来充实自己的腰包。",77,349);
$z[1][4]['name']="description";
$z[2]=Array("field","一般人我不告诉他：八卦帖子赚钱秘诀",351,440);
$z[2][4]['name']="title";
$z[3]=Array("field","",442,481);
$z[3][4]['name']="writer";
$z[4]=Array("field","",483,522);
$z[4][4]['name']="source";
$z[5]=Array("field","",524,564);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",566,603);
$z[6][4]['name']="body";
$z[7]=Array("field","",605,644);
$z[7][4]['name']="litpic";

?>