<?php
$z[0]=Array("field","站长之家, 百度站长平台",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近日，百度正式发布了AppLink服务。“APPLink服务”能让用户通过点击百度搜索结果，调用用户设备中已安装的APP，并进行内容对应的界面。有利于提升APP日活、转化率等核心",75,346);
$z[1][4]['name']="description";
$z[2]=Array("field","百度发布AppLink：可提升移动APP转化率等",348,438);
$z[2][4]['name']="title";
$z[3]=Array("field","",440,479);
$z[3][4]['name']="writer";
$z[4]=Array("field","",481,520);
$z[4][4]['name']="source";
$z[5]=Array("field","",522,562);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",564,601);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AAb0-4SU.png",603,684);
$z[7][4]['name']="litpic";

?>