{dede:field name='keywords'}站长之家, 百度站长平台{/dede:field}
{dede:field name='description'}近日，百度正式发布了AppLink服务。“APPLink服务”能让用户通过点击百度搜索结果，调用用户设备中已安装的APP，并进行内容对应的界面。有利于提升APP日活、转化率等核心{/dede:field}
{dede:field name='title'}百度发布AppLink：可提升移动APP转化率等{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AAb0-4SU.png{/dede:field}
