<?php
$z[0]=Array("field","站长之家, 迅雷CDN, CDN服务",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","随着CDN技术的创新进步，以及迅雷、阿里等互联网厂商出身的CDN服务商越来越多的涌现，传统IDC服务商将面临严峻考验。而在由技术驱动的价格大战当中，网络基础服务成本的降",77,355);
$z[1][4]['name']="description";
$z[2]=Array("field","迅雷再挑价格大战 CDN行业走向何方？",357,444);
$z[2][4]['name']="title";
$z[3]=Array("field","",446,485);
$z[3][4]['name']="writer";
$z[4]=Array("field","",487,526);
$z[4][4]['name']="source";
$z[5]=Array("field","",528,568);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",570,607);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B2J10-32R9.jpg",609,692);
$z[7][4]['name']="litpic";

?>