{dede:field name='keywords'}站长之家, 迅雷CDN, CDN服务{/dede:field}
{dede:field name='description'}随着CDN技术的创新进步，以及迅雷、阿里等互联网厂商出身的CDN服务商越来越多的涌现，传统IDC服务商将面临严峻考验。而在由技术驱动的价格大战当中，网络基础服务成本的降{/dede:field}
{dede:field name='title'}迅雷再挑价格大战 CDN行业走向何方？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B2J10-32R9.jpg{/dede:field}
