<?php
$z[0]=Array("field","站长之家, 百度算法, 搜索",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","我一早就在我的博客说过，我的博客部分内容是伪原创，干货和精华部分是自己原创，但是我就认一个理就是：“这篇文章是否对你有用？”好了这个话题八音猫今天不做过多讨论了",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","2015年5月百度算法做了那些调整？",363,445);
$z[2][4]['name']="title";
$z[3]=Array("field","",447,486);
$z[3][4]['name']="writer";
$z[4]=Array("field","",488,527);
$z[4][4]['name']="source";
$z[5]=Array("field","",529,569);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",571,608);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B24O0-14330.jpg",610,694);
$z[7][4]['name']="litpic";

?>