{dede:field name='keywords'}站长之家, 中新网, 网络安{/dede:field}
{dede:field name='description'}前阵网易服务器宕机、支付宝故障、携程瘫痪还没平息多久，昨日(6月3)，有网友爆料：新闻门户网站“中国新闻网”被黑客攻击。{/dede:field}
{dede:field name='title'}网络安全周中国新闻网被黑并被勒索 疑似DNS劫持{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B03140-33F8.jpg{/dede:field}
