<?php
$z[0]=Array("field","站长之家, 中新网, 网络安",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","前阵网易服务器宕机、支付宝故障、携程瘫痪还没平息多久，昨日(6月3)，有网友爆料：新闻门户网站“中国新闻网”被黑客攻击。",77,293);
$z[1][4]['name']="description";
$z[2]=Array("field","网络安全周中国新闻网被黑并被勒索 疑似DNS劫持",295,397);
$z[2][4]['name']="title";
$z[3]=Array("field","",399,438);
$z[3][4]['name']="writer";
$z[4]=Array("field","",440,479);
$z[4][4]['name']="source";
$z[5]=Array("field","",481,521);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",523,560);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B03140-33F8.jpg",562,646);
$z[7][4]['name']="litpic";

?>