{dede:field name='keywords'}站长之家, Minute, of, Life,{/dede:field}
{dede:field name='description'}好比无意中突然发现自己的口袋里还放着一张毛爷爷的心情是一样的。Minute of Life 就是要让人扫一扫，让人发现惊喜的视频信息服务平台。{/dede:field}
{dede:field name='title'}Minute of Life：扫一扫满是惊喜的视频信息服务{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C33W0-4XM.png{/dede:field}
