<?php
$z[0]=Array("field","站长之家, Githubpages, 百度",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","我在知乎提了这样一个问题：如何解决百度爬虫无法爬取搭建在Github上的个人博客的问题？，并且 Stackoverflow 上也有类似的问题：github blocks Baidu spider, how can I m",76,330);
$z[1][4]['name']="description";
$z[2]=Array("field","解决Github Pages禁止百度爬虫的方法与可行性分析",332,433);
$z[2][4]['name']="title";
$z[3]=Array("field","",435,474);
$z[3][4]['name']="writer";
$z[4]=Array("field","",476,515);
$z[4][4]['name']="source";
$z[5]=Array("field","",517,557);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",559,596);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BU620-323M.png",598,681);
$z[7][4]['name']="litpic";

?>