<?php
$z[0]=Array("field","站长之家, 关键词, 淘宝运",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","传统的选词方法，我就不多说了。今天来说说一种数据选词的方法，不靠直觉，不靠经验，让数据来说话。",77,262);
$z[1][4]['name']="description";
$z[2]=Array("field","淘宝运营之大数据：如何选择正确的关键词？",264,362);
$z[2][4]['name']="title";
$z[3]=Array("field","",364,403);
$z[3][4]['name']="writer";
$z[4]=Array("field","",405,444);
$z[4][4]['name']="source";
$z[5]=Array("field","",446,486);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",488,525);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AI130-4V27.png",527,610);
$z[7][4]['name']="litpic";

?>