{dede:field name='keywords'}站长之家, 域名投资, 域名{/dede:field}
{dede:field name='description'}域名对于大多数的投资人来说，更像是商品。而今天要介绍的这位资深投资人，域名对他来说，更像是收藏品，“我一直觉得其实我是个域名收藏的爱好者”，这位投资人相信不少人{/dede:field}
{dede:field name='title'}路人转粉！一枚域名到底有多少吸引力？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B94350-2JT.jpg{/dede:field}
