<?php
$z[0]=Array("field","站长之家, 域名投资, 域名",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","域名对于大多数的投资人来说，更像是商品。而今天要介绍的这位资深投资人，域名对他来说，更像是收藏品，“我一直觉得其实我是个域名收藏的爱好者”，这位投资人相信不少人",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","路人转粉！一枚域名到底有多少吸引力？",363,455);
$z[2][4]['name']="title";
$z[3]=Array("field","",457,496);
$z[3][4]['name']="writer";
$z[4]=Array("field","",498,537);
$z[4][4]['name']="source";
$z[5]=Array("field","",539,579);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",581,618);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B94350-2JT.jpg",620,703);
$z[7][4]['name']="litpic";

?>