{dede:field name='keywords'}站长之家, CDN服务商, 迅雷{/dede:field}
{dede:field name='description'}6月3日，迅雷CTO、网心科技CEO陈磊在第七届中国云计算大会上宣布迅雷CDN正式接受预定，售价仅为0.1元/GB（流量计价）和9999元/G/月（带宽计价）。霸道的价格剑指互联网新时{/dede:field}
{dede:field name='title'}迅雷发布国内首款无限节点CDN 每GB仅0.1元{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B16210-3R96.jpg{/dede:field}
