<?php
$z[0]=Array("field","站长之家, CDN服务商, 迅雷",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","6月3日，迅雷CTO、网心科技CEO陈磊在第七届中国云计算大会上宣布迅雷CDN正式接受预定，售价仅为0.1元/GB（流量计价）和9999元/G/月（带宽计价）。霸道的价格剑指互联网新时",77,349);
$z[1][4]['name']="description";
$z[2]=Array("field","迅雷发布国内首款无限节点CDN 每GB仅0.1元",351,443);
$z[2][4]['name']="title";
$z[3]=Array("field","",445,484);
$z[3][4]['name']="writer";
$z[4]=Array("field","",486,525);
$z[4][4]['name']="source";
$z[5]=Array("field","",527,567);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",569,606);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B16210-3R96.jpg",608,692);
$z[7][4]['name']="litpic";

?>