<?php
$z[0]=Array("field","站长之家, 微商推广, 微商",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","微商时代，挣钱，不再是靠体力，更不是靠你一天熬八个小时打工，而是靠你思维方式的改变！这是一个观念致富的时代，你在意还是不在意，相信还是不相信，都是一个铁定的事实",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","微商怎么做：怎么加人快又多？",363,443);
$z[2][4]['name']="title";
$z[3]=Array("field","",445,484);
$z[3][4]['name']="writer";
$z[4]=Array("field","",486,525);
$z[4][4]['name']="source";
$z[5]=Array("field","",527,567);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",569,606);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BZU0-41028.jpg",608,691);
$z[7][4]['name']="litpic";

?>