<?php
$z[0]=Array("field","站长之家, O2O创业, O2O创业",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","一九七九年的春天，有一位老人在中国的南海边画了一个圈，这个圈也是现在互联网界的南派代表：深圳。深圳作为改革开放建立的第一个经济特区，“深圳速度”一直引领着国内经",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","O2O创业哪家强 一文了解深圳60多家O2O创业公司",363,461);
$z[2][4]['name']="title";
$z[3]=Array("field","",463,502);
$z[3][4]['name']="writer";
$z[4]=Array("field","",504,543);
$z[4][4]['name']="source";
$z[5]=Array("field","",545,585);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",587,624);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C32120-34c3.jpg",626,710);
$z[7][4]['name']="litpic";

?>