<?php
$z[0]=Array("field","俄罗斯乌兰乌德芭蕾舞剧",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","俄罗斯乌兰乌德芭蕾舞剧院",76,156);
$z[1][4]['name']="description";
$z[2]=Array("field","俄罗斯乌兰乌德芭蕾舞剧院",158,232);
$z[2][4]['name']="title";
$z[3]=Array("field","",234,273);
$z[3][4]['name']="writer";
$z[4]=Array("field","",275,314);
$z[4][4]['name']="source";
$z[5]=Array("field","",316,353);
$z[5][4]['name']="body";
$z[6]=Array("field","",355,395);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",397,661);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c150614/143424a4E50-35510.jpg",663,747);
$z[8][4]['name']="litpic";

?>