{dede:field name='keywords'}站长之家, 百度联盟峰会{/dede:field}
{dede:field name='description'}2015年5月29日，第十届百度联盟峰会在云南腾冲召开。“移动纪元，联创未来”是2015年百度联盟峰会的主题。图为现场照片。{/dede:field}
{dede:field name='title'}{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C930F-22D7.jpg{/dede:field}
