<?php
$z[0]=Array("field","站长之家, 百度联盟峰会",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2015年5月29日，第十届百度联盟峰会在云南腾冲召开。“移动纪元，联创未来”是2015年百度联盟峰会的主题。图为现场照片。",75,283);
$z[1][4]['name']="description";
$z[2]=Array("field","",285,323);
$z[2][4]['name']="title";
$z[3]=Array("field","",325,364);
$z[3][4]['name']="writer";
$z[4]=Array("field","",366,405);
$z[4][4]['name']="source";
$z[5]=Array("field","",407,447);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",449,486);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C930F-22D7.jpg",488,571);
$z[7][4]['name']="litpic";

?>