<?php
$z[0]=Array("field","站长之家, 粉丝运营, SNS推",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","古往今来，“阵法”这个词并不陌生。在互联网品牌营销中其实也是一样，为什么这样说呢？正所谓：“得屌丝者得天下，粉丝才是王道”。",77,307);
$z[1][4]['name']="description";
$z[2]=Array("field","互联网粉丝运营“SNS三剑客”：贴吧、微博、微信",309,413);
$z[2][4]['name']="title";
$z[3]=Array("field","",415,454);
$z[3][4]['name']="writer";
$z[4]=Array("field","",456,495);
$z[4][4]['name']="source";
$z[5]=Array("field","",497,537);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",539,576);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C95010-32S0.png",578,662);
$z[7][4]['name']="litpic";

?>