{dede:field name='keywords'}站长之家, Uber官网, Uber注{/dede:field}
{dede:field name='description'}Uber很少主动营销，但它将用户体验、市场数据、甚至全球一浪高过一浪的围追堵截都变成它的营销利器，快速成长为有史以来估值最高的科技创业公司。{/dede:field}
{dede:field name='title'}Uber生存术，每个司机都是Uber老板{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C21P-25964.jpg{/dede:field}
