<?php
$z[0]=Array("field","站长之家, Uber官网, Uber注",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","Uber很少主动营销，但它将用户体验、市场数据、甚至全球一浪高过一浪的围追堵截都变成它的营销利器，快速成长为有史以来估值最高的科技创业公司。",76,322);
$z[1][4]['name']="description";
$z[2]=Array("field","Uber生存术，每个司机都是Uber老板",324,406);
$z[2][4]['name']="title";
$z[3]=Array("field","",408,447);
$z[3][4]['name']="writer";
$z[4]=Array("field","",449,488);
$z[4][4]['name']="source";
$z[5]=Array("field","",490,530);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",532,569);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C21P-25964.jpg",571,654);
$z[7][4]['name']="litpic";

?>