<?php
$z[0]=Array("field","站长之家, 比特币域名,",0,71);
$z[0][4]['name']="keywords";
$z[1]=Array("field","这几天，国内比特币交易平台OKcoin与比特币著名投资人Roger Ver吵得不可开交。什么情况？这需要从一个千万域名bitcoin.com说起。",73,284);
$z[1][4]['name']="description";
$z[2]=Array("field","一场由“租”来的千万域名引发的口水战",286,378);
$z[2][4]['name']="title";
$z[3]=Array("field","",380,419);
$z[3][4]['name']="writer";
$z[4]=Array("field","",421,460);
$z[4][4]['name']="source";
$z[5]=Array("field","",462,502);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",504,541);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425AO010-350D.png",543,626);
$z[7][4]['name']="litpic";

?>