{dede:field name='keywords'}站长之家, 比特币域名,{/dede:field}
{dede:field name='description'}这几天，国内比特币交易平台OKcoin与比特币著名投资人Roger Ver吵得不可开交。什么情况？这需要从一个千万域名bitcoin.com说起。{/dede:field}
{dede:field name='title'}一场由“租”来的千万域名引发的口水战{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425AO010-350D.png{/dede:field}
