<?php
$z[0]=Array("field","首都机场专机楼",0,62);
$z[0][4]['name']="keywords";
$z[1]=Array("field","首都机场专机楼",64,129);
$z[1][4]['name']="description";
$z[2]=Array("field","首都机场专机楼",131,190);
$z[2][4]['name']="title";
$z[3]=Array("field","",192,231);
$z[3][4]['name']="writer";
$z[4]=Array("field","",233,272);
$z[4][4]['name']="source";
$z[5]=Array("field","",274,311);
$z[5][4]['name']="body";
$z[6]=Array("field","",313,353);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","\r\n{dede:pagestyle maxwidth='800' ddmaxwidth='240' row='3' col='3' value='2'/}\r\n{dede:comments}图集类型会采集时生成此配置是正常的，不过如果后面没有跟着img标记则表示规则无效{/dede:comments}",355,619);
$z[7][4]['name']="imgurls";
$z[8]=Array("field","/uploads/allimg/c150614/143424a430P-3ZT.jpg",621,703);
$z[8][4]['name']="litpic";

?>