{dede:field name='keywords'}站长之家, 汽车之家, 李想{/dede:field}
{dede:field name='description'}汽车之家CEO秦致发内部信表示，过去十年里，李想和公司全体员工同舟共济，为汽车之家的创立和发展做出了卓越贡献，大家在一起亲密而坦诚。未来李想虽然不再参与公司日常的{/dede:field}
{dede:field name='title'}李想当初为什么找秦致当CEO？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C44160-5P96.jpg{/dede:field}
