<?php
$z[0]=Array("field","站长之家, 汽车之家, 李想",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","汽车之家CEO秦致发内部信表示，过去十年里，李想和公司全体员工同舟共济，为汽车之家的创立和发展做出了卓越贡献，大家在一起亲密而坦诚。未来李想虽然不再参与公司日常的",77,358);
$z[1][4]['name']="description";
$z[2]=Array("field","李想当初为什么找秦致当CEO？",360,437);
$z[2][4]['name']="title";
$z[3]=Array("field","",439,478);
$z[3][4]['name']="writer";
$z[4]=Array("field","",480,519);
$z[4][4]['name']="source";
$z[5]=Array("field","",521,561);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",563,600);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C44160-5P96.jpg",602,686);
$z[7][4]['name']="litpic";

?>