{dede:field name='keywords'}站长之家, 秦刚, 社群营销{/dede:field}
{dede:field name='description'}上次我们探讨过社群部落文化，他非常看好这一块的前景，也花了很多的精力陪伴粉丝一起成长，但是当他发现，粉丝来自各行各业，自己不可能以杆子把粉丝的问题全解决的时候，{/dede:field}
{dede:field name='title'}秦刚访谈：如何玩转一个领域社群运营？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B3LF-42643.jpg{/dede:field}
