<?php
$z[0]=Array("field","站长之家, 秦刚, 社群营销",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","上次我们探讨过社群部落文化，他非常看好这一块的前景，也花了很多的精力陪伴粉丝一起成长，但是当他发现，粉丝来自各行各业，自己不可能以杆子把粉丝的问题全解决的时候，",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","秦刚访谈：如何玩转一个领域社群运营？",363,455);
$z[2][4]['name']="title";
$z[3]=Array("field","",457,496);
$z[3][4]['name']="writer";
$z[4]=Array("field","",498,537);
$z[4][4]['name']="source";
$z[5]=Array("field","",539,579);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",581,618);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B3LF-42643.jpg",620,703);
$z[7][4]['name']="litpic";

?>