{dede:field name='keywords'}站长之家, 携程网被黑, 携{/dede:field}
{dede:field name='description'}昨日上午11:09，携程网遭受不明攻击导致官方网站及APP暂时无法正常使用，携程首页挂出通知，建议用户选择艺龙旅行网。{/dede:field}
{dede:field name='title'}携程瘫痪非偶然 国内互联网企业漠视数据管理{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425CA460-11511.jpg{/dede:field}
