<?php
$z[0]=Array("field","站长之家, 携程网被黑, 携",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","昨日上午11:09，携程网遭受不明攻击导致官方网站及APP暂时无法正常使用，携程首页挂出通知，建议用户选择艺龙旅行网。",77,282);
$z[1][4]['name']="description";
$z[2]=Array("field","携程瘫痪非偶然 国内互联网企业漠视数据管理",284,383);
$z[2][4]['name']="title";
$z[3]=Array("field","",385,424);
$z[3][4]['name']="writer";
$z[4]=Array("field","",426,465);
$z[4][4]['name']="source";
$z[5]=Array("field","",467,507);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",509,546);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425CA460-11511.jpg",548,632);
$z[7][4]['name']="litpic";

?>