<?php
$z[0]=Array("field","站长之家, 微商代理, 微商",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","十年以前看淘宝，十年以后看微商。微商外表看起来精彩，暗藏很多玄机，作为一个微商从业者，以一篇文章全部解读微商之艰难。",77,295);
$z[1][4]['name']="description";
$z[2]=Array("field","成功法则：剖析微商怎么做",297,371);
$z[2][4]['name']="title";
$z[3]=Array("field","",373,412);
$z[3][4]['name']="writer";
$z[4]=Array("field","",414,453);
$z[4][4]['name']="source";
$z[5]=Array("field","",455,495);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",497,534);
$z[6][4]['name']="body";
$z[7]=Array("field","",536,575);
$z[7][4]['name']="litpic";

?>