{dede:field name='keywords'}站长之家, 图片社交, 图片{/dede:field}
{dede:field name='description'}社交与社区的区别，无论是因为兴趣图谱还是关系图谱吸引来的用户网络，何必强行区分，内容和关系从事相辅相成的，社交关系依赖内容简历起来，同时也放大了社区的粘性。{/dede:field}
{dede:field name='title'}生于约炮，发展于炫耀，亡于代购，图片社交还能怎么玩？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C1E0-45I7.jpg{/dede:field}
