<?php
$z[0]=Array("field","站长之家, 图片社交, 图片",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","社交与社区的区别，无论是因为兴趣图谱还是关系图谱吸引来的用户网络，何必强行区分，内容和关系从事相辅相成的，社交关系依赖内容简历起来，同时也放大了社区的粘性。",77,355);
$z[1][4]['name']="description";
$z[2]=Array("field","生于约炮，发展于炫耀，亡于代购，图片社交还能怎么玩？",357,473);
$z[2][4]['name']="title";
$z[3]=Array("field","",475,514);
$z[3][4]['name']="writer";
$z[4]=Array("field","",516,555);
$z[4][4]['name']="source";
$z[5]=Array("field","",557,597);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",599,636);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C1E0-45I7.jpg",638,720);
$z[7][4]['name']="litpic";

?>