{dede:field name='keywords'}站长之家, bbbb.com.cn, 域名{/dede:field}
{dede:field name='description'}近日，4声母叠域名bbbb.com.cn昨晚以7.1万元在易名中国结拍，出价次数203次。{/dede:field}
{dede:field name='title'}“撕逼”域名bbbb.com.cn以7.1万元结拍{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C03R0-23594.jpg{/dede:field}
