<?php
$z[0]=Array("field","站长之家, bbbb.com.cn, 域名",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近日，4声母叠域名bbbb.com.cn昨晚以7.1万元在易名中国结拍，出价次数203次。",76,219);
$z[1][4]['name']="description";
$z[2]=Array("field","“撕逼”域名bbbb.com.cn以7.1万元结拍",221,306);
$z[2][4]['name']="title";
$z[3]=Array("field","",308,347);
$z[3][4]['name']="writer";
$z[4]=Array("field","",349,388);
$z[4][4]['name']="source";
$z[5]=Array("field","",390,430);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",432,469);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C03R0-23594.jpg",471,555);
$z[7][4]['name']="litpic";

?>