<?php
$z[0]=Array("field","{##SiteKeyword##}",0,58);
$z[0][4]['name']="keywords";
$z[1]=Array("field","{##SiteDescription##}",60,125);
$z[1][4]['name']="description";
$z[2]=Array("field","2015厦门石材展直播 | 环球石材：我来了，你在哪？",127,232);
$z[2][4]['name']="title";
$z[3]=Array("field","",234,273);
$z[3][4]['name']="writer";
$z[4]=Array("field","",275,314);
$z[4][4]['name']="source";
$z[5]=Array("field","",316,353);
$z[5][4]['name']="body";
$z[6]=Array("field","",355,395);
$z[6][4]['name']="pubdate";
$z[7]=Array("field","/uploads/allimg/c150614/1434245c1560-511O.jpg",397,481);
$z[7][4]['name']="litpic";

?>