<?php
$z[0]=Array("field","站长之家, 网站优化, 网站",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","早先曾经受邀帮助某企业网站进行了一次SEO优化分析，解决这个网站存在的种种不规范的SEO问题，最终提高了该网站整体的页面排名和权重，这里月光博客就和大家分享一下这个案",77,358);
$z[1][4]['name']="description";
$z[2]=Array("field","企业网站SEO优化方案实例",360,431);
$z[2][4]['name']="title";
$z[3]=Array("field","",433,472);
$z[3][4]['name']="writer";
$z[4]=Array("field","",474,513);
$z[4][4]['name']="source";
$z[5]=Array("field","",515,555);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",557,594);
$z[6][4]['name']="body";
$z[7]=Array("field","",596,635);
$z[7][4]['name']="litpic";

?>