{dede:field name='keywords'}{##SiteKeyword##}{/dede:field}
{dede:field name='description'}{##SiteDescription##}{/dede:field}
{dede:field name='title'}环球石材荣获“绿色建筑选用产品”称号{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/1434245b3560-14201.jpg{/dede:field}
