<?php
$z[0]=Array("field","站长之家, 王思聪, bbbb.c",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","此前在微博上喷冰冰和馨予是毯星的国民老公王思聪，却一改往日火上浇油的行事风格，对于这次李晨为新欢和旧爱张馨予发起的撕逼大战一言不发。这让网友们很失望，于是我们可",74,358);
$z[1][4]['name']="description";
$z[2]=Array("field","娱乐圈上演撕逼大戏 王思聪不主持大局只为bbbb.com？",360,467);
$z[2][4]['name']="title";
$z[3]=Array("field","",469,508);
$z[3][4]['name']="writer";
$z[4]=Array("field","",510,549);
$z[4][4]['name']="source";
$z[5]=Array("field","",551,591);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",593,630);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B00010-1L03.jpg",632,716);
$z[7][4]['name']="litpic";

?>