{dede:field name='keywords'}站长之家, 王思聪, bbbb.c{/dede:field}
{dede:field name='description'}此前在微博上喷冰冰和馨予是毯星的国民老公王思聪，却一改往日火上浇油的行事风格，对于这次李晨为新欢和旧爱张馨予发起的撕逼大战一言不发。这让网友们很失望，于是我们可{/dede:field}
{dede:field name='title'}娱乐圈上演撕逼大戏 王思聪不主持大局只为bbbb.com？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B00010-1L03.jpg{/dede:field}
