<?php
$z[0]=Array("field","站长之家, 创业孵化器, 女",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","你可能以为这是个噱头，但Girl up确实在认真做孵化这件事。",77,200);
$z[1][4]['name']="description";
$z[2]=Array("field","专门孵化美女创业者的Girl up： 怎样让姐姐妹妹“站起来”？",202,320);
$z[2][4]['name']="title";
$z[3]=Array("field","",322,361);
$z[3][4]['name']="writer";
$z[4]=Array("field","",363,402);
$z[4][4]['name']="source";
$z[5]=Array("field","",404,444);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",446,483);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C35440-513I.jpg",485,569);
$z[7][4]['name']="litpic";

?>