{dede:field name='keywords'}站长之家, 创业孵化器, 女{/dede:field}
{dede:field name='description'}你可能以为这是个噱头，但Girl up确实在认真做孵化这件事。{/dede:field}
{dede:field name='title'}专门孵化美女创业者的Girl up： 怎样让姐姐妹妹“站起来”？{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C35440-513I.jpg{/dede:field}
