<?php
$z[0]=Array("field","站长之家, 网站优化, 内容",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","网站内容更新，Baiduspider才会爬行网站完成收录。但是笔者小丹发现自百度“取消”快照后，尤其是进入五月份后不必说文章收录了，就是爬行记录都少得可怜。到底现在的网站",77,354);
$z[1][4]['name']="description";
$z[2]=Array("field","现在网站内容更新要怎么做？",356,433);
$z[2][4]['name']="title";
$z[3]=Array("field","",435,474);
$z[3][4]['name']="writer";
$z[4]=Array("field","",476,515);
$z[4][4]['name']="source";
$z[5]=Array("field","",517,557);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",559,596);
$z[6][4]['name']="body";
$z[7]=Array("field","",598,637);
$z[7][4]['name']="litpic";

?>