{dede:field name='keywords'}站长之家, 果心科技, 智能{/dede:field}
{dede:field name='description'}果心科技以后也会有可能在智能锁的基础上推出其他智能家居产品，但是否会接入苹果的 Homekit 平台，目前还没有考虑太多。{/dede:field}
{dede:field name='title'}是的，一定有不需要带钥匙的办法{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C13V0-15561.jpg{/dede:field}
