<?php
$z[0]=Array("field","站长之家, 果心科技, 智能",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","果心科技以后也会有可能在智能锁的基础上推出其他智能家居产品，但是否会接入苹果的 Homekit 平台，目前还没有考虑太多。",77,286);
$z[1][4]['name']="description";
$z[2]=Array("field","是的，一定有不需要带钥匙的办法",288,371);
$z[2][4]['name']="title";
$z[3]=Array("field","",373,412);
$z[3][4]['name']="writer";
$z[4]=Array("field","",414,453);
$z[4][4]['name']="source";
$z[5]=Array("field","",455,495);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",497,534);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C13V0-15561.jpg",536,620);
$z[7][4]['name']="litpic";

?>