<?php
$z[0]=Array("field","站长之家, VPS主机, Conoha",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","这些年来，美国VPS主机遍地都是，而日本、新加坡等VPS主机则因为支付方式等原因的限制往往都不好买，即便是买到了也会有不少的使用问题。",74,307);
$z[1][4]['name']="description";
$z[2]=Array("field","Conoha.jp日本新加坡美国VPS主机申请、管理等",309,404);
$z[2][4]['name']="title";
$z[3]=Array("field","",406,445);
$z[3][4]['name']="writer";
$z[4]=Array("field","",447,486);
$z[4][4]['name']="source";
$z[5]=Array("field","",488,528);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",530,567);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425BXR0-2K16.jpg",569,651);
$z[7][4]['name']="litpic";

?>