{dede:noteinfo notename="建站经验" channelid="1" macthtype="string"
    refurl="http://" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://www.chinaz.com/web/exp/(*).shtml"
startid="1" endid="5" addv="1" urlrule="area" musthas="2015"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.chinaz.com/start/{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="newsListBar current">{/dede:areastart}
    {dede:areaend}<div class="pagecon tc clearfix ptb25">{/dede:areaend}
{/dede:listrule}
{dede:sppage sptype='full' srul='1' erul='5'}{/dede:sppage}
{dede:previewurl}http://www.chinaz.com/start/2015/0612/413990.shtml{/dede:previewurl}
{dede:keywordtrim}{/dede:keywordtrim}
{dede:descriptiontrim}{/dede:descriptiontrim}
{dede:item field='title' value='' isunit='' isdown=''}
   {dede:match}<h1 class="YaHei">[内容]</h1>{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='writer' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='source' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='pubdate' value='' isunit='' isdown=''}
   {dede:match}{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}{dede:item field='body' value='' isunit='1' isdown='1'}
   {dede:match}<div id="ctrlfscont">[内容]</div>
            </div>
                        <div class="pagebreak pageBar tc mtb20">{/dede:match}
   
   {dede:function}{/dede:function}
{/dede:item}