{dede:field name='keywords'}站长之家, 淘宝店铺, 店铺{/dede:field}
{dede:field name='description'}2015年是淘宝政策大变革的一年，PC端的流量越来越少不说，更有品牌商和KA店铺两座大山横亘在广大中小卖家眼前。PC端中小卖家举步维艰，无线端趁势大起，个性化搜索加强。可{/dede:field}
{dede:field name='title'}实操案例：教你如何玩转个性化搜索！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C05L0-4C60.jpg{/dede:field}
