<?php
$z[0]=Array("field","站长之家, 淘宝店铺, 店铺",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","2015年是淘宝政策大变革的一年，PC端的流量越来越少不说，更有品牌商和KA店铺两座大山横亘在广大中小卖家眼前。PC端中小卖家举步维艰，无线端趁势大起，个性化搜索加强。可",77,356);
$z[1][4]['name']="description";
$z[2]=Array("field","实操案例：教你如何玩转个性化搜索！",358,447);
$z[2][4]['name']="title";
$z[3]=Array("field","",449,488);
$z[3][4]['name']="writer";
$z[4]=Array("field","",490,529);
$z[4][4]['name']="source";
$z[5]=Array("field","",531,571);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",573,610);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C05L0-4C60.jpg",612,695);
$z[7][4]['name']="litpic";

?>