{dede:field name='keywords'}站长之家, 百度站长平台{/dede:field}
{dede:field name='description'}今日，百度站长平台发布就“PC站点移动化”问题发布了公告。据公告显示，百度方面已将PC移动化方式规范化，目前主要分为三种方式：跳转适配、代码适配和自适应。且升级了移{/dede:field}
{dede:field name='title'}百度站长平台：移动sitemap协议mobile type升级{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B5A50-3D47.jpg{/dede:field}
