<?php
$z[0]=Array("field","站长之家, 百度站长平台",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","今日，百度站长平台发布就“PC站点移动化”问题发布了公告。据公告显示，百度方面已将PC移动化方式规范化，目前主要分为三种方式：跳转适配、代码适配和自适应。且升级了移",75,357);
$z[1][4]['name']="description";
$z[2]=Array("field","百度站长平台：移动sitemap协议mobile type升级",359,454);
$z[2][4]['name']="title";
$z[3]=Array("field","",456,495);
$z[3][4]['name']="writer";
$z[4]=Array("field","",497,536);
$z[4][4]['name']="source";
$z[5]=Array("field","",538,578);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",580,617);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B5A50-3D47.jpg",619,702);
$z[7][4]['name']="litpic";

?>