<?php
$z[0]=Array("field","站长之家, PPG网站, 凡客网",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","PPG的兴起也给已然全速行驶的电子商务带来了一针强心剂，一刹那，全国几乎到处都是卖衬衣的网站。陈年的凡客也是在这个时候开始酝酿的。",77,310);
$z[1][4]['name']="description";
$z[2]=Array("field","PPG的成与败和凡客神奇的路",312,386);
$z[2][4]['name']="title";
$z[3]=Array("field","",388,427);
$z[3][4]['name']="writer";
$z[4]=Array("field","",429,468);
$z[4][4]['name']="source";
$z[5]=Array("field","",470,510);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",512,549);
$z[6][4]['name']="body";
$z[7]=Array("field","",551,590);
$z[7][4]['name']="litpic";

?>