{dede:field name='keywords'}站长之家, PPG网站, 凡客网{/dede:field}
{dede:field name='description'}PPG的兴起也给已然全速行驶的电子商务带来了一针强心剂，一刹那，全国几乎到处都是卖衬衣的网站。陈年的凡客也是在这个时候开始酝酿的。{/dede:field}
{dede:field name='title'}PPG的成与败和凡客神奇的路{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
