{dede:field name='keywords'}站长之家, le.com, 乐视网{/dede:field}
{dede:field name='description'}4月份，“乐”域名le.com交易的消息传出，当时买家身份扑朔迷离，乐视网呼声最高，如今谜团渐渐解开，买家Lenovation应是联想旗下的控股子公司，坊间传闻该笔交易价格超100{/dede:field}
{dede:field name='title'}不是乐视网买的？曝联想超6千万元购域名le.com{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C560-12A6.jpg{/dede:field}
