<?php
$z[0]=Array("field","站长之家, le.com, 乐视网",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","4月份，“乐”域名le.com交易的消息传出，当时买家身份扑朔迷离，乐视网呼声最高，如今谜团渐渐解开，买家Lenovation应是联想旗下的控股子公司，坊间传闻该笔交易价格超100",74,348);
$z[1][4]['name']="description";
$z[2]=Array("field","不是乐视网买的？曝联想超6千万元购域名le.com",350,449);
$z[2][4]['name']="title";
$z[3]=Array("field","",451,490);
$z[3][4]['name']="writer";
$z[4]=Array("field","",492,531);
$z[4][4]['name']="source";
$z[5]=Array("field","",533,573);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",575,612);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C560-12A6.jpg",614,696);
$z[7][4]['name']="litpic";

?>