{dede:field name='keywords'}站长之家, HTTPS加密, 美国{/dede:field}
{dede:field name='description'}美国政府发布一项计划，HTTPS将成为公共网站联邦安全标准，其目标是到2016年12月31日，让美国联邦政府所有网站都使用HTTPS加密。{/dede:field}
{dede:field name='title'}HTTPS-Only标准：美国所有政府网站将使用HTTPS加密{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425C11110-5EO.png{/dede:field}
