<?php
$z[0]=Array("field","站长之家, HTTPS加密, 美国",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","美国政府发布一项计划，HTTPS将成为公共网站联邦安全标准，其目标是到2016年12月31日，让美国联邦政府所有网站都使用HTTPS加密。",76,291);
$z[1][4]['name']="description";
$z[2]=Array("field","HTTPS-Only标准：美国所有政府网站将使用HTTPS加密",293,394);
$z[2][4]['name']="title";
$z[3]=Array("field","",396,435);
$z[3][4]['name']="writer";
$z[4]=Array("field","",437,476);
$z[4][4]['name']="source";
$z[5]=Array("field","",478,518);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",520,557);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425C11110-5EO.png",559,642);
$z[7][4]['name']="litpic";

?>