<?php
$z[0]=Array("field","站长之家, 百度联盟, 博客",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","对于中文类的博客赚钱的模式其实我一直没有放弃过探索，尤其是对部落这个自己第一个建立起来的中文网站更是“呵护”有加，也一直是我建站的“试验场”。部落博客其实也一直",77,361);
$z[1][4]['name']="description";
$z[2]=Array("field","博客盈利：百度联盟账号被封及解封过程分析",363,461);
$z[2][4]['name']="title";
$z[3]=Array("field","",463,502);
$z[3][4]['name']="writer";
$z[4]=Array("field","",504,543);
$z[4][4]['name']="source";
$z[5]=Array("field","",545,585);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",587,624);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B25J0-225Z.jpg",626,709);
$z[7][4]['name']="litpic";

?>