{dede:field name='keywords'}站长之家, 人人影视复活{/dede:field}
{dede:field name='description'}今日，人人影视发布公告表示，原人人影视更名为人人影视网站大全，且已停用旧域名yyets.com，跳转至新域名allyingshi.com。{/dede:field}
{dede:field name='title'}人人影视改名后回归了！还换了个有点难记的新域名{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425B62920-16111.png{/dede:field}
