<?php
$z[0]=Array("field","站长之家, 人人影视复活",0,73);
$z[0][4]['name']="keywords";
$z[1]=Array("field","今日，人人影视发布公告表示，原人人影视更名为人人影视网站大全，且已停用旧域名yyets.com，跳转至新域名allyingshi.com。",75,280);
$z[1][4]['name']="description";
$z[2]=Array("field","人人影视改名后回归了！还换了个有点难记的新域名",282,389);
$z[2][4]['name']="title";
$z[3]=Array("field","",391,430);
$z[3][4]['name']="writer";
$z[4]=Array("field","",432,471);
$z[4][4]['name']="source";
$z[5]=Array("field","",473,513);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",515,552);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425B62920-16111.png",554,639);
$z[7][4]['name']="litpic";

?>