{dede:field name='keywords'}站长之家, 携程被攻击, 携{/dede:field}
{dede:field name='description'}昨日，携程上演了“天地大冲撞”的灾难剧情。来自携程官方的最新消息是：“携程app已经恢复，官网产品正在逐步恢复中。”{/dede:field}
{dede:field name='title'}攻击、代码与流言：携程灾难全记录{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c150614/143425CB430-2Z42.jpg{/dede:field}
