<?php
$z[0]=Array("field","站长之家, 携程被攻击, 携",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","昨日，携程上演了“天地大冲撞”的灾难剧情。来自携程官方的最新消息是：“携程app已经恢复，官网产品正在逐步恢复中。”",77,289);
$z[1][4]['name']="description";
$z[2]=Array("field","攻击、代码与流言：携程灾难全记录",291,377);
$z[2][4]['name']="title";
$z[3]=Array("field","",379,418);
$z[3][4]['name']="writer";
$z[4]=Array("field","",420,459);
$z[4][4]['name']="source";
$z[5]=Array("field","",461,501);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",503,540);
$z[6][4]['name']="body";
$z[7]=Array("field","/uploads/allimg/c150614/143425CB430-2Z42.jpg",542,625);
$z[7][4]['name']="litpic";

?>