<?php
$z[0]=Array("global","",322,349);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",879,904);
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",979,1004);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("channelartlist","\r\n<li><a class=\"hide\" href='{dede:field name='typeurl'/}'>{dede:field name='typename'/}</a>\r\n<ul>\r\n<div class=\"jianjiao\"><img src=\"/skins/jianjiao.png\" width=\"20\" height=\"6\" alt=\"\"></div>\r\n{dede:channel type='son' noself='true'}\r\n<li><a href='[field:typelink/]'>[field:typename/]</a></li>\r\n{/dede:channel}\r\n</ul>\r\n</li>\r\n",2291,2674);
$z[3][4]['row']="7";
$z[3][4]['typeid']="top";

?>