<?php
$z[0]=Array("field","",109,128);
$z[0][4]['name']="title";
$z[1]=Array("global","",129,155);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",196,225);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",265,323);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",570,605);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1036,1065);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n",1073,1250);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[7]=Array("list","\r\n<li><a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\" title=\"[field:title/]\" width=\"290\" height=\"215\"></a>\r\n<h1><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></h1>\r\n</li>\r\n",1427,1684);
$z[7][4]['pagesize']="12";
$z[8]=Array("pagelist","",1845,1923);
$z[8][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1967,2004);
$z[9][4]['filename']="footer.htm";

?>