<?php
$z[0]=Array("field","",109,128);
$z[0][4]['name']="title";
$z[1]=Array("global","",129,155);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",196,225);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",265,323);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",570,605);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",988,1017);
$z[5][4]['name']="position";
$z[6]=Array("channel","\r\n<li><a href='[field:typeurl/]'>[field:typename/]</a></li>\r\n",1025,1202);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li><a href='~typelink~' class='current'>~typename~</a></li>";
$z[7]=Array("field","",1359,1380);
$z[7][4]['name']="content";
$z[8]=Array("include","",1461,1498);
$z[8][4]['filename']="footer.htm";

?>